{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GTNewHorizons",
    "module": "neiaddons",
    "version": "1.17.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "NotEnoughItems",
          "version": {
            "requires": "2.7.87-GTNH"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "NotEnoughItems",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        }
      ],
      "files": [
        {
          "name": "neiaddons-1.17.0-dev.jar",
          "url": "neiaddons-1.17.0-dev.jar",
          "size": 143259,
          "sha512": "faee15a1a425c9a924edd439731b985f66a6213a95ef3f04ae693400fa4494d1d066d1b2c2383ab6e6ec88ba5a20f13df52b90efd51851afb6c3193b63f66e04",
          "sha256": "2ffb70d449d6adaf86ea253cc46361a73a72f2b797d5dc8c4b359e06af0781b9",
          "sha1": "3cba412d0813cca2e1d75a4d1ea0cd4128bd269f",
          "md5": "72fa1d084f27886b9679d5803a69a124"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "ForestryMC",
          "version": {
            "requires": "4.10.17"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "ForestryMC",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "waila",
          "version": {
            "requires": "1.8.13"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "waila",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "NotEnoughItems",
          "version": {
            "requires": "2.7.87-GTNH"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "NotEnoughItems",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.6.37"
          },
          "reason": "fixes duplicate mod errors in java 17 configurations using old gtnhlib"
        }
      ],
      "files": [
        {
          "name": "neiaddons-1.17.0-dev.jar",
          "url": "neiaddons-1.17.0-dev.jar",
          "size": 143259,
          "sha512": "faee15a1a425c9a924edd439731b985f66a6213a95ef3f04ae693400fa4494d1d066d1b2c2383ab6e6ec88ba5a20f13df52b90efd51851afb6c3193b63f66e04",
          "sha256": "2ffb70d449d6adaf86ea253cc46361a73a72f2b797d5dc8c4b359e06af0781b9",
          "sha1": "3cba412d0813cca2e1d75a4d1ea0cd4128bd269f",
          "md5": "72fa1d084f27886b9679d5803a69a124"
        }
      ]
    },
    {
      "name": "reobfElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "srg",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "neiaddons-1.17.0.jar",
          "url": "neiaddons-1.17.0.jar",
          "size": 145396,
          "sha512": "43cede241d243fb577c698d2c1c10efa52b49f19de6d4948637947b155d1517c301f48898d27eb23c4947570af503bbcec6a3bfbf6e9d38a9562adac88bcf474",
          "sha256": "bfac8b5ff2c2b67a3a0d6e6eea791279f97c7de65fc9488e77f974e7bf75967a",
          "sha1": "9f1eaf9f5b7198c5c39bb25de02a2f6886911330",
          "md5": "5d9adde37dead1d823dda048fa68c859"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "neiaddons-1.17.0-sources.jar",
          "url": "neiaddons-1.17.0-sources.jar",
          "size": 106205,
          "sha512": "9d802cee48ab4ca245c8a5d1cc5720b6705c1c7fc57ef9ce281c2ed1be82088d356dcba651e15d0dc1849e3b8fa517fd47f5ef6c5e045ff94cc5189f9ce413ae",
          "sha256": "e1861388614ea0bd70e6676ad4b60ec38caee5f77c97b41a3b298ec68359a675",
          "sha1": "63f4135554a9b79c9758210a5ef18c8ede9471d7",
          "md5": "d1c7d113c2681d5c0cc5c6343fbf2cd4"
        }
      ]
    }
  ]
}
