{
  "formatVersion" : "1.1",
  "component" : {
    "group" : "com.github.ElytraServers",
    "module" : "elytra-conventions",
    "version" : "v1.1.1",
    "attributes" : {
      "org.gradle.status" : "release"
    }
  },
  "createdBy" : {
    "gradle" : {
      "version" : "8.13"
    }
  },
  "variants" : [ {
    "name" : "apiElements",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.jvm.environment" : "standard-jvm",
      "org.gradle.jvm.version" : "17",
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-api",
      "org.jetbrains.kotlin.platform.type" : "jvm"
    },
    "files" : [ {
      "name" : "plugin-v1.1.1.jar",
      "url" : "plugin-v1.1.1.jar",
      "size" : 39245,
      "sha512" : "557f2c6f98319e18c0839d2354c5763e6748de341c1a650f4d8d694fdb55944a65d6a936daf1556c310e67e948bb901222ab33197a7fb254c1504e7a6f8fe472",
      "sha256" : "c8ed5118e4944ee76d7bf2ef09e99a36e71ccf695f51896d809089b128e8aaaf",
      "sha1" : "df1954e11bbdd4c1e7004c2980bf5b09fa42dc57",
      "md5" : "2b03135ffddf8d12e36305ed7c2c392d"
    } ]
  }, {
    "name" : "runtimeElements",
    "attributes" : {
      "org.gradle.category" : "library",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.jvm.environment" : "standard-jvm",
      "org.gradle.jvm.version" : "17",
      "org.gradle.libraryelements" : "jar",
      "org.gradle.usage" : "java-runtime",
      "org.jetbrains.kotlin.platform.type" : "jvm"
    },
    "dependencies" : [ {
      "group" : "com.google.code.gson",
      "module" : "gson",
      "version" : {
        "requires" : "2.13.1"
      }
    } ],
    "files" : [ {
      "name" : "plugin-v1.1.1.jar",
      "url" : "plugin-v1.1.1.jar",
      "size" : 39245,
      "sha512" : "557f2c6f98319e18c0839d2354c5763e6748de341c1a650f4d8d694fdb55944a65d6a936daf1556c310e67e948bb901222ab33197a7fb254c1504e7a6f8fe472",
      "sha256" : "c8ed5118e4944ee76d7bf2ef09e99a36e71ccf695f51896d809089b128e8aaaf",
      "sha1" : "df1954e11bbdd4c1e7004c2980bf5b09fa42dc57",
      "md5" : "2b03135ffddf8d12e36305ed7c2c392d"
    } ]
  }, {
    "name" : "sourcesElements",
    "attributes" : {
      "org.gradle.category" : "documentation",
      "org.gradle.dependency.bundling" : "external",
      "org.gradle.docstype" : "sources",
      "org.gradle.usage" : "java-runtime"
    },
    "files" : [ {
      "name" : "plugin-v1.1.1.jar",
      "url" : "plugin-v1.1.1.jar",
      "size" : 8230,
      "sha512" : "4bc004fd70f63017965adabae83de50237cc712f502f0946bf6b21ce844f1c1594cedd98134d8cc5d4e9cc923fd671cfbe5693018f3d2f0abf7f6e7b96297fa8",
      "sha256" : "906d497b1e35b9db9712f108e3d996b0ad64eb9fe03f5992efc967f25f7b2022",
      "sha1" : "a13bb682c21a74e1bdee85b6a4f6227e7ee4873f",
      "md5" : "611e6e80cd701f27fc0d9894766a7d64"
    } ]
  } ]
}