{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GTNewHorizons",
    "module": "ModularUI",
    "version": "1.2.20",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "NotEnoughItems",
          "version": {
            "requires": "2.7.59-GTNH"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "NotEnoughItems",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ModularUI-1.2.20-dev.jar",
          "url": "ModularUI-1.2.20-dev.jar",
          "size": 474169,
          "sha512": "6c00cf47dc6b3ee12fff13f26534265945cabde39464f489e778d2c958219d3dfe66144069a94f0b725623b34725915b8e6fd7e9ffaeea2f8fc2e6031d139d40",
          "sha256": "eda1500d1465aa5abf7a48c2ec7dd8799d416dd77b6d46cc2672d5c3cd1b9538",
          "sha1": "04ad38663744aab85aa78bcdb025e98c2d0c9540",
          "md5": "43202d575c6e03b9f792a5bcba7c31d1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.legacymoddingmc",
          "module": "unimixins",
          "version": {
            "requires": "0.1.20"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "unimixins",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.6.32"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "GTNHLib",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "23.0.0"
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "NotEnoughItems",
          "version": {
            "requires": "2.7.59-GTNH"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "NotEnoughItems",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.6.13"
          },
          "reason": "fixes duplicate mod errors in java 17 configurations using old gtnhlib"
        }
      ],
      "files": [
        {
          "name": "ModularUI-1.2.20-dev.jar",
          "url": "ModularUI-1.2.20-dev.jar",
          "size": 474169,
          "sha512": "6c00cf47dc6b3ee12fff13f26534265945cabde39464f489e778d2c958219d3dfe66144069a94f0b725623b34725915b8e6fd7e9ffaeea2f8fc2e6031d139d40",
          "sha256": "eda1500d1465aa5abf7a48c2ec7dd8799d416dd77b6d46cc2672d5c3cd1b9538",
          "sha1": "04ad38663744aab85aa78bcdb025e98c2d0c9540",
          "md5": "43202d575c6e03b9f792a5bcba7c31d1"
        }
      ]
    },
    {
      "name": "reobfElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "srg",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ModularUI-1.2.20.jar",
          "url": "ModularUI-1.2.20.jar",
          "size": 481062,
          "sha512": "edbc4965c5fdc4f3a406a3ab77da8c5fae75398cea92bbcdb4a75df1e46f7f0d03b44bd221d36bf238e7f864b966eb645378a8fd9420eb52710f1ca86113a4c4",
          "sha256": "21a8ce9fc4d731f7d8d4a3d12c71f7564aa65402901b5d19bbbddb7ac1e975cd",
          "sha1": "8e0850c805c4340492ec5ff141cee31cf09cf24d",
          "md5": "d75cd2d475bb0ed0411d641e52ed80db"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ModularUI-1.2.20-sources.jar",
          "url": "ModularUI-1.2.20-sources.jar",
          "size": 239111,
          "sha512": "4211d43fccf404ea38d650b1a7a0bdb61cfd005a2b88332f42652c4a2ce610a67887b1082ba4720dc06b59ae32cfeb1a5bdfd3772b812f71f5f4181c659ceac5",
          "sha256": "2362d537d897e3c214d4f9db8446685abda05dc5353377f714af353bbe0d3d1f",
          "sha1": "2e35dfe07d9ad8cff8cc426cc32373bfcf2e5831",
          "md5": "c379e329d970d69b4498cd92886076ef"
        }
      ]
    }
  ]
}
