{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GTNewHorizons",
    "module": "supersolarpanels",
    "version": "1.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "net.industrial-craft",
          "module": "industrialcraft-2",
          "version": {
            "requires": "2.2.828-experimental"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "industrialcraft-2",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        }
      ],
      "files": [
        {
          "name": "supersolarpanels-1.1.4-dev.jar",
          "url": "supersolarpanels-1.1.4-dev.jar",
          "size": 65487,
          "sha512": "6a8afca71e558a871add88121917e66e7a20dfc6919d917c53f95633c067733962b8ca4ae419d96f80578094c444685baf5cb114f168f129508e3cca628b0738",
          "sha256": "8b15a9d02a58fe3b2eb136f268312d380d455ad45f485645bf17e4093d7db323",
          "sha1": "93203668e5406cf3e8779f512ffa51f5dcc1be59",
          "md5": "8daf7ada4026f6d0593d60106a3e7a7b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "advsolar-362768",
          "version": {
            "requires": "2885953"
          }
        },
        {
          "group": "net.industrial-craft",
          "module": "industrialcraft-2",
          "version": {
            "requires": "2.2.828-experimental"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "industrialcraft-2",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.6.13"
          },
          "reason": "fixes duplicate mod errors in java 17 configurations using old gtnhlib"
        }
      ],
      "files": [
        {
          "name": "supersolarpanels-1.1.4-dev.jar",
          "url": "supersolarpanels-1.1.4-dev.jar",
          "size": 65487,
          "sha512": "6a8afca71e558a871add88121917e66e7a20dfc6919d917c53f95633c067733962b8ca4ae419d96f80578094c444685baf5cb114f168f129508e3cca628b0738",
          "sha256": "8b15a9d02a58fe3b2eb136f268312d380d455ad45f485645bf17e4093d7db323",
          "sha1": "93203668e5406cf3e8779f512ffa51f5dcc1be59",
          "md5": "8daf7ada4026f6d0593d60106a3e7a7b"
        }
      ]
    },
    {
      "name": "reobfElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "srg",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "supersolarpanels-1.1.4.jar",
          "url": "supersolarpanels-1.1.4.jar",
          "size": 66573,
          "sha512": "6c91b5eda62095a25b10fdbab94ad3b5b10f08a4118d00319d3ae08fc63a8f8f2fc7969715bca27db572d3ea73db78daa3e585932a70e5e66d5fff5e1ef12eea",
          "sha256": "6acdbd4f940bc90c595c51248ba2a830a4e3741bc16ae0d06c68dd91463d1928",
          "sha1": "d2cdeceeec23b3c6bbc76a4d16a11ffd157dcec2",
          "md5": "d9cac979bff7e798f79514de6c1be553"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "supersolarpanels-1.1.4-sources.jar",
          "url": "supersolarpanels-1.1.4-sources.jar",
          "size": 55296,
          "sha512": "dd673bbf0185eabe39b59d524fb07bece6caddbf443409010be0627946817cae888937b453a82d5c51e0a1b38bc26a97d80306b4ec7ceb77da79611c87e0ad69",
          "sha256": "09f11702c4e10ca1b25e89f735c9b96b35df91793a8a7230a505979f6e708fac",
          "sha1": "a7cb2eaaff3c336f66f55a650542e71684ff9b5f",
          "md5": "9e8786374aed2a7dbf4a9400a62522e0"
        }
      ]
    }
  ]
}
