{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinpoet/2.2.0/kotlinpoet-2.2.0.module",
    "group": "com.squareup",
    "module": "kotlinpoet",
    "version": "2.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinpoet-jvm-2.2.0.jar",
          "url": "kotlinpoet-jvm-2.2.0.jar",
          "size": 357262,
          "sha512": "e6c9a6eb46b0f290cd412aced209f5d9d0ecd439eed06d48c82e5a537a58af4cf7e25bd6eee1d8079cf65dc2ca4a21954285b53902d721ef967cb73ff8b9f7ab",
          "sha256": "87ba83576e2bbda929e2d4d83035eaf7984b9adc0798837b8e8d1eb4953a17da",
          "sha1": "9360941958f3650a0b9be685bebd6eef290e3b9b",
          "md5": "542c8e2843352ba2f607c6b1511e7999"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinpoet-jvm-2.2.0.jar",
          "url": "kotlinpoet-jvm-2.2.0.jar",
          "size": 357262,
          "sha512": "e6c9a6eb46b0f290cd412aced209f5d9d0ecd439eed06d48c82e5a537a58af4cf7e25bd6eee1d8079cf65dc2ca4a21954285b53902d721ef967cb73ff8b9f7ab",
          "sha256": "87ba83576e2bbda929e2d4d83035eaf7984b9adc0798837b8e8d1eb4953a17da",
          "sha1": "9360941958f3650a0b9be685bebd6eef290e3b9b",
          "md5": "542c8e2843352ba2f607c6b1511e7999"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlinpoet-jvm-2.2.0-sources.jar",
          "url": "kotlinpoet-jvm-2.2.0-sources.jar",
          "size": 92717,
          "sha512": "a7971444fc3f6fc1af9d0876ea6507a2877d1af92cd1b681fe3e0c233764a8e21363ab00629c3519dd1ebeb97e6cdc13fba49ae0fe2821d850b9c6874652c496",
          "sha256": "c402466241327cf5c80ccb0979b982db43efd5a7d2ca7a5fa70b89127dc7ab87",
          "sha1": "bc90c6663548060bf7b998ec536973c942198dd7",
          "md5": "9f74d939c41f72734e7d4719d1a4880a"
        }
      ]
    }
  ]
}
