{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GTNewHorizons",
    "module": "CodeChickenLib",
    "version": "1.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "CodeChickenLib-1.3.0-dev.jar",
          "url": "CodeChickenLib-1.3.0-dev.jar",
          "size": 317617,
          "sha512": "a0aef5de8ec84d88efbd7a4c475b3e8e1423e5ce5faf4f1a27d4dbc07ede11d6d8a0da397d638aa896440bc905e536554bb2ccc41626762ddc034e550cc91dee",
          "sha256": "65e9d797f065f307b4602d41586e5d60ed8ee050d4b8eadcc40529ffa88058f0",
          "sha1": "42666d43d896be23e0ed83317dd033a359c54d5a",
          "md5": "6a37db13b27e25a9619ec4909b3dc94a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.2.11"
          },
          "reason": "fixes duplicate mod errors in java 17 configurations using old gtnhlib"
        }
      ],
      "files": [
        {
          "name": "CodeChickenLib-1.3.0-dev.jar",
          "url": "CodeChickenLib-1.3.0-dev.jar",
          "size": 317617,
          "sha512": "a0aef5de8ec84d88efbd7a4c475b3e8e1423e5ce5faf4f1a27d4dbc07ede11d6d8a0da397d638aa896440bc905e536554bb2ccc41626762ddc034e550cc91dee",
          "sha256": "65e9d797f065f307b4602d41586e5d60ed8ee050d4b8eadcc40529ffa88058f0",
          "sha1": "42666d43d896be23e0ed83317dd033a359c54d5a",
          "md5": "6a37db13b27e25a9619ec4909b3dc94a"
        }
      ]
    },
    {
      "name": "reobfElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "srg",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "CodeChickenLib-1.3.0.jar",
          "url": "CodeChickenLib-1.3.0.jar",
          "size": 319472,
          "sha512": "ed2e1cfa87eb064dd4bfc86a2dd8266768683d408534aa7f36dc72026d29c743a471ac7142b8d734fdf1092343dd1f9496318b3a2e7478bc8b5e2a7a83acc7da",
          "sha256": "44f57f35713a11c922a527b457af77dbd0c79b50dad86f8354b471ba105c1264",
          "sha1": "86d55951dcfc8c71f17aa6b718cdfb688ae04177",
          "md5": "1cd1167a8b8aa6a759748a37aa54bd92"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "CodeChickenLib-1.3.0-sources.jar",
          "url": "CodeChickenLib-1.3.0-sources.jar",
          "size": 138985,
          "sha512": "ce3f5c613f9eba3a38b8c8c98accdc95271222fef1350c45bac39ac8eaf9261a9651f86e0c781fd4a0042d11c0012ddd93fdd22f1f38923bb7d0ef19f36899c5",
          "sha256": "e22e590103b33d5456d64d51c99aa9670f91cfccb498ff13e1b6fd3f924afd05",
          "sha1": "ede3f45997b236a0bdc26661b43db10e559cfde6",
          "md5": "ea401e0f055aa39101b49bf1b03ea63a"
        }
      ]
    }
  ]
}
