{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GTNewHorizons",
    "module": "Natura",
    "version": "2.8.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "Mantle",
          "version": {
            "requires": "0.5.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "Mantle",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        }
      ],
      "files": [
        {
          "name": "Natura-2.8.9-dev.jar",
          "url": "Natura-2.8.9-dev.jar",
          "size": 877521,
          "sha512": "826978f131d5aa33808b662146454f1a25695bc3b0de6244438e208dd87a7d2b1a114ceedc3c0744448b68d6365e0bbf476c632f3768955c4a1bcc5caa761ae6",
          "sha256": "a04494d5b9a0a6a9809418438695058717014ebfe894dd8e32036d12d641b42b",
          "sha1": "ee67a353960514f176d4a6b260f87832c309f433",
          "md5": "ae0568c24f5e58f1748a7d11ec50acaa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "Mantle",
          "version": {
            "requires": "0.5.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "Mantle",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.6.37"
          },
          "reason": "fixes duplicate mod errors in java 17 configurations using old gtnhlib"
        }
      ],
      "files": [
        {
          "name": "Natura-2.8.9-dev.jar",
          "url": "Natura-2.8.9-dev.jar",
          "size": 877521,
          "sha512": "826978f131d5aa33808b662146454f1a25695bc3b0de6244438e208dd87a7d2b1a114ceedc3c0744448b68d6365e0bbf476c632f3768955c4a1bcc5caa761ae6",
          "sha256": "a04494d5b9a0a6a9809418438695058717014ebfe894dd8e32036d12d641b42b",
          "sha1": "ee67a353960514f176d4a6b260f87832c309f433",
          "md5": "ae0568c24f5e58f1748a7d11ec50acaa"
        }
      ]
    },
    {
      "name": "reobfElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "srg",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Natura-2.8.9.jar",
          "url": "Natura-2.8.9.jar",
          "size": 888955,
          "sha512": "7a671d90cdb7a1e6ddddb4b1425dcf5ca8c5f2b72ffc4817f9f4eb110717f3d3ba88de781f1d765237e4a8fbce932c68ade030b095b2d725fdfa8daf8cba5e50",
          "sha256": "d85e979a3ef38d20e6d025fa1e1e43057ef10a63f51975a39f28c3687e4c7b81",
          "sha1": "df95fc1c2f035842b4a9dfdf483ade17ed051c5a",
          "md5": "4b85538e41db58a6c3e04850dded0c8e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Natura-2.8.9-sources.jar",
          "url": "Natura-2.8.9-sources.jar",
          "size": 713094,
          "sha512": "11e74b83aaac524eda71e54217449c7df9275de321edbb93f3fd314854995ea77bd8ceb415063b2352af86c4efd43fc60f4be5d049a89a8701f69ca3ff5233aa",
          "sha256": "d4735be31db5c72ad5ea14e06fc65fc16777d063c9cbcee6bb1b8c8f49172ace",
          "sha1": "31ded0757c198b5a298840a129374e452005e432",
          "md5": "a2a77b097bd64dc8189b7160dae2aeba"
        }
      ]
    }
  ]
}
