{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GTNewHorizons",
    "module": "ProjectRed",
    "version": "4.11.13-GTNH",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "ForgeMultipart",
          "version": {
            "requires": "1.6.8"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "ForgeMultipart",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "ForgeRelocation",
          "version": {
            "requires": "0.3.4"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "ForgeRelocation",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ProjectRed-4.11.13-GTNH-dev.jar",
          "url": "ProjectRed-4.11.13-GTNH-dev.jar",
          "size": 10401362,
          "sha512": "7ef3bb702eb44de322f6ecde7d3da6ce57883ec92dea651a05df54525715719d9a5a62ac60fbf3bae7f860bbc38a9dc57ac28578556ee8e3658c1a517754c714",
          "sha256": "65e1a90a46c94233de48f23f54ca24dbb184d3975688a07ecaddbf9b4c691fd7",
          "sha1": "39f857dc5c8d73dcbd6479bde6dc79a26e8cc9c1",
          "md5": "3b970f941a2340613e650a907c802633"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "NotEnoughItems",
          "version": {
            "requires": "2.7.77-GTNH"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "NotEnoughItems",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "ForgeMultipart",
          "version": {
            "requires": "1.6.8"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "ForgeMultipart",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "ForgeRelocation",
          "version": {
            "requires": "0.3.4"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "ForgeRelocation",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.6.37"
          },
          "reason": "fixes duplicate mod errors in java 17 configurations using old gtnhlib"
        }
      ],
      "files": [
        {
          "name": "ProjectRed-4.11.13-GTNH-dev.jar",
          "url": "ProjectRed-4.11.13-GTNH-dev.jar",
          "size": 10401362,
          "sha512": "7ef3bb702eb44de322f6ecde7d3da6ce57883ec92dea651a05df54525715719d9a5a62ac60fbf3bae7f860bbc38a9dc57ac28578556ee8e3658c1a517754c714",
          "sha256": "65e1a90a46c94233de48f23f54ca24dbb184d3975688a07ecaddbf9b4c691fd7",
          "sha1": "39f857dc5c8d73dcbd6479bde6dc79a26e8cc9c1",
          "md5": "3b970f941a2340613e650a907c802633"
        }
      ]
    },
    {
      "name": "reobfElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "srg",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ProjectRed-4.11.13-GTNH.jar",
          "url": "ProjectRed-4.11.13-GTNH.jar",
          "size": 10457047,
          "sha512": "d2daffeb8a7022cf59e9d5bd5a2adc222c0d081dc33f7d7485bcc0695e1b733a0b7095c04561d721ed9462414d8ffa16ee05a3275fc09a1314f903c91b2c4683",
          "sha256": "e3943d882b41d5c58492636b7a8418b491eed95accfeaf19f748cc06ea72a8ae",
          "sha1": "00a407cb33c6fb0b8ec4c1fac7dbd3a5b97f5382",
          "md5": "14f16b3ee4a867f3ac17b382b33d49cf"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ProjectRed-4.11.13-GTNH-sources.jar",
          "url": "ProjectRed-4.11.13-GTNH-sources.jar",
          "size": 7166141,
          "sha512": "ffb59e481105daeaf8cef20ce495eb709b0def288ff8ee5de7fef034e4a7aa912a28354877ca25221660c1642d33ed3eec36cef6ee2109faeb6559869dc0feaf",
          "sha256": "4e42850cc89791527e93480ac8c700a4f974380462f1230bd0f6a63bff6fe86f",
          "sha1": "39bb48fa16b369e0af99ec00171c12f4b6b74d81",
          "md5": "8532a702f7727bff024c00afced49e83"
        }
      ]
    }
  ]
}
