{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GTNewHorizons",
    "module": "NewHorizonsCoreMod",
    "version": "2.7.260",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "GT5-Unofficial",
          "version": {
            "requires": "5.09.51.466"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "GT5-Unofficial",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "Yamcl",
          "version": {
            "requires": "0.7.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "Yamcl",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "Baubles-Expanded",
          "version": {
            "requires": "2.1.15-GTNH"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "Baubles-Expanded",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "Mobs-Info",
          "version": {
            "requires": "0.5.4-GTNH"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "Mobs-Info",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        }
      ],
      "files": [
        {
          "name": "NewHorizonsCoreMod-2.7.260-dev.jar",
          "url": "NewHorizonsCoreMod-2.7.260-dev.jar",
          "size": 12347603,
          "sha512": "834dc01de0cd36a87940c43c35b55a5a79156f0ba20ed6bd94e9fece0325f3ce2f2dbee34aa559328f9beb061b48dfdc24ae64a6b5bd238d10983c44732bb8bd",
          "sha256": "77f07d6c30fa3d6f38eab06ae1e505c4a177924b79ac425fba757521f74e9db2",
          "sha1": "d2a4d793dd6931948592c639a9d51d6b03d0bb86",
          "md5": "56a8e37f0e4f06d0beff8dbdc600373b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.legacymoddingmc",
          "module": "unimixins",
          "version": {
            "requires": "0.1.23"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "unimixins",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.6.40"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "GTNHLib",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "net.glease",
          "module": "tc4recipelib",
          "version": {
            "requires": "1.5.37"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "tc4recipelib",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "GT5-Unofficial",
          "version": {
            "requires": "5.09.51.466"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "GT5-Unofficial",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "Yamcl",
          "version": {
            "requires": "0.7.1"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "Yamcl",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "Baubles-Expanded",
          "version": {
            "requires": "2.1.15-GTNH"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "Baubles-Expanded",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.6.37"
          },
          "reason": "fixes duplicate mod errors in java 17 configurations using old gtnhlib"
        }
      ],
      "files": [
        {
          "name": "NewHorizonsCoreMod-2.7.260-dev.jar",
          "url": "NewHorizonsCoreMod-2.7.260-dev.jar",
          "size": 12347603,
          "sha512": "834dc01de0cd36a87940c43c35b55a5a79156f0ba20ed6bd94e9fece0325f3ce2f2dbee34aa559328f9beb061b48dfdc24ae64a6b5bd238d10983c44732bb8bd",
          "sha256": "77f07d6c30fa3d6f38eab06ae1e505c4a177924b79ac425fba757521f74e9db2",
          "sha1": "d2a4d793dd6931948592c639a9d51d6b03d0bb86",
          "md5": "56a8e37f0e4f06d0beff8dbdc600373b"
        }
      ]
    },
    {
      "name": "reobfElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "srg",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NewHorizonsCoreMod-2.7.260.jar",
          "url": "NewHorizonsCoreMod-2.7.260.jar",
          "size": 12360423,
          "sha512": "7d2dcc2e91efe54a984d6be8695b56918ea8b58f1181d2394d5672d1e3e86f049adfffe6f5d83a60b59f538f9073a75085ca6696a6d8ed4091ac91d8581623fa",
          "sha256": "6971b2e320a69a6bdf8ff54bebc7d50b1906ce2656271ea64880f01017bfa1c3",
          "sha1": "43ac0d173c398f5199e51c237c01b581f5b5dd6c",
          "md5": "32c7f773c8806af604a3fdd1e444559b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NewHorizonsCoreMod-2.7.260-sources.jar",
          "url": "NewHorizonsCoreMod-2.7.260-sources.jar",
          "size": 11500240,
          "sha512": "0e99549dce5ed6aa6559b59412ff5caeb1cd5da25c842afa42d19bd3bd469d497dce51bba875ca6ab0e2e88013b84ecdc1a2dfa5fff569e41e17b83fd353a186",
          "sha256": "830931a3dd5f9cbad5331b823fb399d6d453fac18f6803df835de15c186c0aec",
          "sha1": "80a4e7efecae5b19df84c92b97a6dc949d00d0ef",
          "md5": "72c172a048e6108a039cc5f711aa85c0"
        }
      ]
    }
  ]
}
