{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GTNewHorizons",
    "module": "Applied-Energistics-2-Unofficial",
    "version": "rv3-beta-689-GTNH",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "Angelica",
          "version": {
            "requires": "1.0.0-beta56"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "Angelica",
              "type": "jar",
              "extension": "jar",
              "classifier": "api"
            }
          }
        }
      ],
      "files": [
        {
          "name": "Applied-Energistics-2-Unofficial-rv3-beta-689-GTNH-dev.jar",
          "url": "Applied-Energistics-2-Unofficial-rv3-beta-689-GTNH-dev.jar",
          "size": 3776400,
          "sha512": "e0001233ad275e85db52f6f2e269ae54b88b1d2045a89f845a5407bb9b59375cbe6bbd340e2ead2fb9f051c3654c6cbb87391dc7a0b63b6acaff0bf2d9bcf812",
          "sha256": "6415bc1b899a4b3e0c798dcc36eae338394808f2f48bbe5148e459a49beee44f",
          "sha1": "f955e5d253811dcd638ba32d9bfcbb7cfb687897",
          "md5": "8ca46eebdab833365056db0b39e44690"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "NotEnoughItems",
          "version": {
            "requires": "2.7.87-GTNH"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "NotEnoughItems",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.6.39"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "GTNHLib",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "curse.maven",
          "module": "cofh-core-69162",
          "version": {
            "requires": "2388751"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.6.37"
          },
          "reason": "fixes duplicate mod errors in java 17 configurations using old gtnhlib"
        }
      ],
      "files": [
        {
          "name": "Applied-Energistics-2-Unofficial-rv3-beta-689-GTNH-dev.jar",
          "url": "Applied-Energistics-2-Unofficial-rv3-beta-689-GTNH-dev.jar",
          "size": 3776400,
          "sha512": "e0001233ad275e85db52f6f2e269ae54b88b1d2045a89f845a5407bb9b59375cbe6bbd340e2ead2fb9f051c3654c6cbb87391dc7a0b63b6acaff0bf2d9bcf812",
          "sha256": "6415bc1b899a4b3e0c798dcc36eae338394808f2f48bbe5148e459a49beee44f",
          "sha1": "f955e5d253811dcd638ba32d9bfcbb7cfb687897",
          "md5": "8ca46eebdab833365056db0b39e44690"
        }
      ]
    },
    {
      "name": "reobfElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "srg",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Applied-Energistics-2-Unofficial-rv3-beta-689-GTNH.jar",
          "url": "Applied-Energistics-2-Unofficial-rv3-beta-689-GTNH.jar",
          "size": 3805459,
          "sha512": "8bcb9883e5d6d92c6c28d5128aba430facfff3cfe8d6771d96e2ef06fca07dda53ce8b6dcf987663897ecd20b5216b4f95f32d5971eacde126c890fc98ee8aba",
          "sha256": "8c6a18aafe288f89317190bd2c060441188ac70942b27bd30faa22b0ac71bb2c",
          "sha1": "6d42a8692f6de52328e6f5cc474832986839b544",
          "md5": "85696d64c38e7a00786800dd300e67c6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Applied-Energistics-2-Unofficial-rv3-beta-689-GTNH-sources.jar",
          "url": "Applied-Energistics-2-Unofficial-rv3-beta-689-GTNH-sources.jar",
          "size": 2899398,
          "sha512": "9f15e685134f1c49b71f6283c28176295baa89d118af9e571d27d6f3b57419ab2abee2c14f8f74385823ca02fc8ee1eeb8d26cffba9c55ba1881637702b0209d",
          "sha256": "b481dcac75f098dc5df369a441741dc0604a3b03a92576d8b420fb6ae5fb39eb",
          "sha1": "2401a18acf1c931e751669d0795d9800bba5bb6f",
          "md5": "40348f81599f23aa10816474e3bbc4ee"
        }
      ]
    }
  ]
}
