{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GTNewHorizons",
    "module": "Universal-Singularities",
    "version": "8.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "Avaritia",
          "version": {
            "requires": "1.59"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "Avaritia",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        }
      ],
      "files": [
        {
          "name": "Universal-Singularities-8.10.0-dev.jar",
          "url": "Universal-Singularities-8.10.0-dev.jar",
          "size": 18750,
          "sha512": "10eedb78bd6b0b69abab48cafba8b69b1c2504d35859e6587762d15081c7bb2d13029f7955711721e94b93906210a67290bb00b596e5df3a6ed9dd06c79053a2",
          "sha256": "5198b44aa5214181f94c7619eaca47531ca3ad4455aabfbe7a031acd81c551c0",
          "sha1": "4b4bbc09007148f1c5f80c1d880af8091acfc373",
          "md5": "f639d2ce70672a6425ad6c9bf40fae48"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "Avaritia",
          "version": {
            "requires": "1.59"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "Avaritia",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.5.21"
          },
          "reason": "fixes duplicate mod errors in java 17 configurations using old gtnhlib"
        }
      ],
      "files": [
        {
          "name": "Universal-Singularities-8.10.0-dev.jar",
          "url": "Universal-Singularities-8.10.0-dev.jar",
          "size": 18750,
          "sha512": "10eedb78bd6b0b69abab48cafba8b69b1c2504d35859e6587762d15081c7bb2d13029f7955711721e94b93906210a67290bb00b596e5df3a6ed9dd06c79053a2",
          "sha256": "5198b44aa5214181f94c7619eaca47531ca3ad4455aabfbe7a031acd81c551c0",
          "sha1": "4b4bbc09007148f1c5f80c1d880af8091acfc373",
          "md5": "f639d2ce70672a6425ad6c9bf40fae48"
        }
      ]
    },
    {
      "name": "reobfElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "srg",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Universal-Singularities-8.10.0.jar",
          "url": "Universal-Singularities-8.10.0.jar",
          "size": 19175,
          "sha512": "ea5ec8af067e2ece4b6c9ee1c1c7c9c0a85a936aca1f8d426bdf179f20658544902f1dc1be4c89469e24020dd9963600a45f5734cc38b703282a5b74c2a159f5",
          "sha256": "b06c5e659f4cf2d5526632f505c4cd873884dd797a489ff610eb4c953ce53efa",
          "sha1": "bc9118af9018f8c7de37c3a46f19c6301090b814",
          "md5": "53ff0528446d5d045d234bb2f591ba07"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Universal-Singularities-8.10.0-sources.jar",
          "url": "Universal-Singularities-8.10.0-sources.jar",
          "size": 13149,
          "sha512": "861cc83730931924a81caab83dcb4ed056342ebb76bfe131d34e3b16b51f040b8c06479326b45fc3d4e6fae97503e1779c9424b520acea59a2b5cc6397382212",
          "sha256": "41f87fd04cbe3ba9e3aec656176b51004518891c7dab688bb945fa665272bfff",
          "sha1": "7226fb9140c401fede777904bbc8cd99b8b56194",
          "md5": "32ad08a1a337d06746cd648eb655ed6f"
        }
      ]
    }
  ]
}
