{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GTNewHorizons",
    "module": "Applied-Energistics-2-Unofficial",
    "version": "rv3-beta-690-GTNH",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "Angelica",
          "version": {
            "requires": "1.0.0-beta56"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "Angelica",
              "type": "jar",
              "extension": "jar",
              "classifier": "api"
            }
          }
        }
      ],
      "files": [
        {
          "name": "Applied-Energistics-2-Unofficial-rv3-beta-690-GTNH-dev.jar",
          "url": "Applied-Energistics-2-Unofficial-rv3-beta-690-GTNH-dev.jar",
          "size": 3776263,
          "sha512": "91af797226aa3e90a62b98249377bbcbcc998511e0add197099d6183593d89eac20c31c2b5bf26d1473d2ea130b5a14026a2a8cff59319c3ca3f4c557a70e7aa",
          "sha256": "598041f4055d9dc7c1e5adf3794bc9f1f1a6d840b30c298437d5928363b41bae",
          "sha1": "63147ef225b89395bd9fd0864d7819474ef40cf1",
          "md5": "6f882b3ee565a607f43683d0fec9cb41"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "NotEnoughItems",
          "version": {
            "requires": "2.7.87-GTNH"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "NotEnoughItems",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.6.39"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "GTNHLib",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "curse.maven",
          "module": "cofh-core-69162",
          "version": {
            "requires": "2388751"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.6.37"
          },
          "reason": "fixes duplicate mod errors in java 17 configurations using old gtnhlib"
        }
      ],
      "files": [
        {
          "name": "Applied-Energistics-2-Unofficial-rv3-beta-690-GTNH-dev.jar",
          "url": "Applied-Energistics-2-Unofficial-rv3-beta-690-GTNH-dev.jar",
          "size": 3776263,
          "sha512": "91af797226aa3e90a62b98249377bbcbcc998511e0add197099d6183593d89eac20c31c2b5bf26d1473d2ea130b5a14026a2a8cff59319c3ca3f4c557a70e7aa",
          "sha256": "598041f4055d9dc7c1e5adf3794bc9f1f1a6d840b30c298437d5928363b41bae",
          "sha1": "63147ef225b89395bd9fd0864d7819474ef40cf1",
          "md5": "6f882b3ee565a607f43683d0fec9cb41"
        }
      ]
    },
    {
      "name": "reobfElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "srg",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Applied-Energistics-2-Unofficial-rv3-beta-690-GTNH.jar",
          "url": "Applied-Energistics-2-Unofficial-rv3-beta-690-GTNH.jar",
          "size": 3805302,
          "sha512": "d995886207f5ba52a64e97750f18eb89ec9d6ea03bc9fb0a66029714e7f66daf44c8876ca3b9c36c7a61c758e490268475faf57b9e3bd3d9005873f9ff840a5a",
          "sha256": "850bc2bab4c9b791d49c25c902c462db751a3fa377bf96eb6f9e9299c0c096c1",
          "sha1": "c3518b18ec737d7cac09815cbda7d6ebb8fe02ad",
          "md5": "6fd8767ddf1ecd83b48dd4086cdf6c82"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Applied-Energistics-2-Unofficial-rv3-beta-690-GTNH-sources.jar",
          "url": "Applied-Energistics-2-Unofficial-rv3-beta-690-GTNH-sources.jar",
          "size": 2899260,
          "sha512": "7550f4e9d8352ce7e1abe745e919ee74bf18c800b4d9d780417af7371bc8ed8ba231bb12202dc7f3fd0d40d48cd413559b77dd8bea504e2bea4e463758b1fb66",
          "sha256": "b899e2b8d1e6be1d694880c1796e8c6634b338cb66dc366c0115ba939043d857",
          "sha1": "e77e7b70f81714ca1659ae01544644e25ad17e2d",
          "md5": "40d334ce1207b249a7eba60a3e3666cc"
        }
      ]
    }
  ]
}
