{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GTNewHorizons",
    "module": "NotEnoughIds",
    "version": "2.1.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.6.36"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "GTNHLib",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        }
      ],
      "files": [
        {
          "name": "NotEnoughIds-2.1.10-dev.jar",
          "url": "NotEnoughIds-2.1.10-dev.jar",
          "size": 64562,
          "sha512": "ce8beeaf07bdf62ea9b7774a97606aa98c73157f3d8fd2a9057dcefec2e276abce6297fd78569d772945c415cee7d2744ba1fbaff92eb07337f18ee574f7901a",
          "sha256": "0ebd4e1e0af6ea5a79cb9941d86b20545c8af16a5ff41e643de8128d9c61332c",
          "sha1": "0a89e8514f3f670c4c5169310171f71bb86b3a8b",
          "md5": "3f3d91fce7edf2d97f4491c09d9d26b5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.legacymoddingmc",
          "module": "unimixins",
          "version": {
            "requires": "0.1.22"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "unimixins",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.6.36"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "GTNHLib",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.6.13"
          },
          "reason": "fixes duplicate mod errors in java 17 configurations using old gtnhlib"
        }
      ],
      "files": [
        {
          "name": "NotEnoughIds-2.1.10-dev.jar",
          "url": "NotEnoughIds-2.1.10-dev.jar",
          "size": 64562,
          "sha512": "ce8beeaf07bdf62ea9b7774a97606aa98c73157f3d8fd2a9057dcefec2e276abce6297fd78569d772945c415cee7d2744ba1fbaff92eb07337f18ee574f7901a",
          "sha256": "0ebd4e1e0af6ea5a79cb9941d86b20545c8af16a5ff41e643de8128d9c61332c",
          "sha1": "0a89e8514f3f670c4c5169310171f71bb86b3a8b",
          "md5": "3f3d91fce7edf2d97f4491c09d9d26b5"
        }
      ]
    },
    {
      "name": "reobfElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "srg",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NotEnoughIds-2.1.10.jar",
          "url": "NotEnoughIds-2.1.10.jar",
          "size": 65491,
          "sha512": "80f49287f1064dd381b660ef05ec4e6917670d8bd35321e1806e9faaf797d7c228dd72013a05a9560c5ff1d26bc88c11d4e5ba14b7b3f757b07363d7a81a896d",
          "sha256": "b48446a5612458d404f40dac1f22ae5fbdc4208cd7b0c913148fda937cbd5cc4",
          "sha1": "878ee142047e03a4b7394ccbf1862f878e95e7e7",
          "md5": "c7e91e352d7bdde7605f29b7426e2c0a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NotEnoughIds-2.1.10-sources.jar",
          "url": "NotEnoughIds-2.1.10-sources.jar",
          "size": 43781,
          "sha512": "2a22654f9df010e0f252630b1062d9e02f9f425705d2f953db88350cbc41d0e803f94ead4a7f44926b9c83141a51431855474807d492d0fe88e1c94df7ea5b35",
          "sha256": "b590de1743561b037d19843f2fd25c547555ab239ebc6214bb650f22062f933e",
          "sha1": "00d86385b2bb64ecbea6fd568908e0f186b6426c",
          "md5": "1d234820f899bd69dddf799ac0352e55"
        }
      ]
    }
  ]
}
