{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GTNewHorizons",
    "module": "BrandonsCore",
    "version": "1.2.0-GTNH",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "BrandonsCore-1.2.0-GTNH-dev.jar",
          "url": "BrandonsCore-1.2.0-GTNH-dev.jar",
          "size": 80790,
          "sha512": "d4ab38a017f14df3daccfd350ac0bbf7f442b201a38e8fa772f42a5d4e20d959d0dce44da40c7c5d1209158cde25480f7f78bcd1a3f66a381c4f8a8d1f41cdbb",
          "sha256": "4616b7ec5048ad2185fb40ac3b0101be86afea26e5ceff8df33aa6371204dbe6",
          "sha1": "a099d3e4b6ad5388f1c4bd4ee2ef04bcc4a0f008",
          "md5": "2a95cbf1c6677cdad7b2d1ae717cb20c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.2.11"
          },
          "reason": "fixes duplicate mod errors in java 17 configurations using old gtnhlib"
        }
      ],
      "files": [
        {
          "name": "BrandonsCore-1.2.0-GTNH-dev.jar",
          "url": "BrandonsCore-1.2.0-GTNH-dev.jar",
          "size": 80790,
          "sha512": "d4ab38a017f14df3daccfd350ac0bbf7f442b201a38e8fa772f42a5d4e20d959d0dce44da40c7c5d1209158cde25480f7f78bcd1a3f66a381c4f8a8d1f41cdbb",
          "sha256": "4616b7ec5048ad2185fb40ac3b0101be86afea26e5ceff8df33aa6371204dbe6",
          "sha1": "a099d3e4b6ad5388f1c4bd4ee2ef04bcc4a0f008",
          "md5": "2a95cbf1c6677cdad7b2d1ae717cb20c"
        }
      ]
    },
    {
      "name": "reobfElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "srg",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "BrandonsCore-1.2.0-GTNH.jar",
          "url": "BrandonsCore-1.2.0-GTNH.jar",
          "size": 82137,
          "sha512": "6c5021d25abc00e8dcdaebfdc0ed6c9a29721183555320fa7e7158336c2bf6c320c6cde64912fd41f4d445144549873ec84f084563a5a9492f8124a7db0237fd",
          "sha256": "a57cc303e89eb091fb88c0d6b4bd4952befbb2b116f91ad4590a76076a2d8f84",
          "sha1": "4504075138aeb156023d7324e6de24d39a44b70c",
          "md5": "2af992f6f442679a6f98657e6ae131e6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "BrandonsCore-1.2.0-GTNH-sources.jar",
          "url": "BrandonsCore-1.2.0-GTNH-sources.jar",
          "size": 51124,
          "sha512": "3154fdc329b2af9c4a0925491bfd48a97a792eef180c3e9fb85cd700c8e5d50ccf23150364e1a539d84edac65e73c92f910eb84e3fc2442df8b0146438ef6fcc",
          "sha256": "1815dd64bcfdf55ed609bec58cfa34429e5b55ffcf6af374f4d059099ad45c9f",
          "sha1": "73b422b5508ed520b9acd5ebfe9bb54fb8cdb24e",
          "md5": "7870d0e97a582d4aff0ddc0273f43625"
        }
      ]
    }
  ]
}
