{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GTNewHorizons",
    "module": "ThaumicTinkerer",
    "version": "2.11.26",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "Baubles-Expanded",
          "version": {
            "requires": "2.1.15-GTNH"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "Baubles-Expanded",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "thaumcraft",
          "module": "Thaumcraft",
          "version": {
            "requires": "1.7.10-4.2.3.5"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "Thaumcraft",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "Applied-Energistics-2-Unofficial",
          "version": {
            "requires": "rv3-beta-688-GTNH"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "Applied-Energistics-2-Unofficial",
              "type": "jar",
              "extension": "jar",
              "classifier": "api"
            }
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "ThaumicBoots",
          "version": {
            "requires": "1.4.14"
          },
          "excludes": [
            {
              "group": "*",
              "module": "Baubles"
            },
            {
              "group": "com.github.GTNewHorizons",
              "module": "Electro-Magic-Tools"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "ThaumicBoots",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ThaumicTinkerer-2.11.26-dev.jar",
          "url": "ThaumicTinkerer-2.11.26-dev.jar",
          "size": 2039429,
          "sha512": "33d772e9efdd26675ba8d30e325e4bd4c127b9ffd84b081c1e2162ef63c915af09a88e615a88282f1f30925b11c50b001157140bd5922ac27097180a2d2582f6",
          "sha256": "b6edd4e01fa16e89efa218def453abf7ad2764a80e08880ad9ed849e548087b7",
          "sha1": "c4f2ea86b0467dabe28177ad75750f0220353803",
          "md5": "423a1cc022d0fddad4f79a845714f668"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.legacymoddingmc",
          "module": "unimixins",
          "version": {
            "requires": "0.1.23"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "unimixins",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "Baubles-Expanded",
          "version": {
            "requires": "2.1.15-GTNH"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "Baubles-Expanded",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "thaumcraft",
          "module": "Thaumcraft",
          "version": {
            "requires": "1.7.10-4.2.3.5"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "Thaumcraft",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "Applied-Energistics-2-Unofficial",
          "version": {
            "requires": "rv3-beta-688-GTNH"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "Applied-Energistics-2-Unofficial",
              "type": "jar",
              "extension": "jar",
              "classifier": "api"
            }
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "ThaumicBoots",
          "version": {
            "requires": "1.4.14"
          },
          "excludes": [
            {
              "group": "*",
              "module": "Baubles"
            },
            {
              "group": "com.github.GTNewHorizons",
              "module": "Electro-Magic-Tools"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "ThaumicBoots",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "TCNEIAdditions",
          "version": {
            "requires": "1.5.4"
          },
          "excludes": [
            {
              "group": "*",
              "module": "Baubles"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "TCNEIAdditions",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.6.37"
          },
          "reason": "fixes duplicate mod errors in java 17 configurations using old gtnhlib"
        }
      ],
      "files": [
        {
          "name": "ThaumicTinkerer-2.11.26-dev.jar",
          "url": "ThaumicTinkerer-2.11.26-dev.jar",
          "size": 2039429,
          "sha512": "33d772e9efdd26675ba8d30e325e4bd4c127b9ffd84b081c1e2162ef63c915af09a88e615a88282f1f30925b11c50b001157140bd5922ac27097180a2d2582f6",
          "sha256": "b6edd4e01fa16e89efa218def453abf7ad2764a80e08880ad9ed849e548087b7",
          "sha1": "c4f2ea86b0467dabe28177ad75750f0220353803",
          "md5": "423a1cc022d0fddad4f79a845714f668"
        }
      ]
    },
    {
      "name": "reobfElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "srg",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ThaumicTinkerer-2.11.26.jar",
          "url": "ThaumicTinkerer-2.11.26.jar",
          "size": 2044301,
          "sha512": "b13c6d26642aeef0a397a8fcd6a929627c42f26112b6c7a529fcfbd128fc87024412660dbab4369a433f1b69d1fa3e59d79c905838173caecd928de735547c73",
          "sha256": "ba54eed406776c513bfde2f027709667ee9ca85cbec61c9611ccdb87e37f4db0",
          "sha1": "6b493718845c7e42e5f6de9b33bba75cf16c4f55",
          "md5": "71a5c38c3402702b23f4f4b653a0faae"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ThaumicTinkerer-2.11.26-sources.jar",
          "url": "ThaumicTinkerer-2.11.26-sources.jar",
          "size": 1761337,
          "sha512": "d353a5d90e6ba4f43481db9fe7602df773b413d04ffcb97192351510bdb77402a1caa4f80b600229c208e6244cb910e89d968125bed1a9cefa41ce835cc93b1e",
          "sha256": "1191b194530fc29da912c0624f8d547976e84dec24e56a366a9942eb91b50a00",
          "sha1": "e4cb2cafc6afc2d2e58fca269dd675628f99f7ee",
          "md5": "c3df9978ff04df6a15efc8337718a385"
        }
      ]
    }
  ]
}
