{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GTNewHorizons",
    "module": "bdlib",
    "version": "1.11.0-GTNH",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "bdlib-1.11.0-GTNH-dev.jar",
          "url": "bdlib-1.11.0-GTNH-dev.jar",
          "size": 1518951,
          "sha512": "8ae54b0c2fa45622591eade8692ba45ba615ec92e364a067ec4365036e79e5167d45a6187dcdfbf0ee419b07741a99bc88b1e17e5e1fef433fff4b1e953c2059",
          "sha256": "153befadbb10cf586db7f3669c28c7c639bcded82c4065990162552b4d0dc5b4",
          "sha1": "232b0a37b0cd44c914cdb339be2fb39bc0a3a332",
          "md5": "e93ef044707a63ef7a71ffe55187512f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.6.13"
          },
          "reason": "fixes duplicate mod errors in java 17 configurations using old gtnhlib"
        }
      ],
      "files": [
        {
          "name": "bdlib-1.11.0-GTNH-dev.jar",
          "url": "bdlib-1.11.0-GTNH-dev.jar",
          "size": 1518951,
          "sha512": "8ae54b0c2fa45622591eade8692ba45ba615ec92e364a067ec4365036e79e5167d45a6187dcdfbf0ee419b07741a99bc88b1e17e5e1fef433fff4b1e953c2059",
          "sha256": "153befadbb10cf586db7f3669c28c7c639bcded82c4065990162552b4d0dc5b4",
          "sha1": "232b0a37b0cd44c914cdb339be2fb39bc0a3a332",
          "md5": "e93ef044707a63ef7a71ffe55187512f"
        }
      ]
    },
    {
      "name": "reobfElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "srg",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bdlib-1.11.0-GTNH.jar",
          "url": "bdlib-1.11.0-GTNH.jar",
          "size": 1537651,
          "sha512": "d1f4680c189e21e668cd76e604289ca00456643d0c4ace8ad08836097fed218ba2f5a965fb51bd0d00c20017257a3d58a205848bba469a3705f9b46a465de819",
          "sha256": "130e6e88b8a3340a7518eef3ba313877b7a08149693980fa10c5d8b4f9da3095",
          "sha1": "cb33b381109b16dfb22707b1256ba3cf31979606",
          "md5": "ecfca8b447911c58a421a8f9bab96785"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "bdlib-1.11.0-GTNH-sources.jar",
          "url": "bdlib-1.11.0-GTNH-sources.jar",
          "size": 180573,
          "sha512": "e02a0cf929ee41366b955017e068edc2915c8bfc7294f0caba8bcbca79f2a23159e7fd4dced30c351a7d46a5d3eee52d6d295ce8b0f3fea09f35669081ddebe1",
          "sha256": "d2cbebb5f14be606329feaaf1247d6fe10d4333f01b1f9ad12fb6d55fed10e8d",
          "sha1": "53c93f3a824d75a2f3f77f0df605be018d180535",
          "md5": "f878791d169eb17868e151a28163110b"
        }
      ]
    }
  ]
}
