{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GTNewHorizons",
    "module": "worldedit-gtnh",
    "version": "v0.0.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "worldedit-gtnh-v0.0.8-dev.jar",
          "url": "worldedit-gtnh-v0.0.8-dev.jar",
          "size": 1402883,
          "sha512": "a00990c90f11174c8a271f508907f319731765ec4de146a720148c5b46397c16d5ea4436442e47e0575594bc9325238f39d4122aaaa272d2192b9aa690b7cf3b",
          "sha256": "c4e7d10bb9827cf37e2cfcadbddaa91165b51f3e85ae56bdcec80b18fca79b60",
          "sha1": "d6d04ccd871242e7556b015798ce7692e4d9601c",
          "md5": "0b61c3ad1828cc99b704583176633d06"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "de.schlichtherle",
          "module": "truezip",
          "version": {
            "requires": "6.8.3"
          }
        },
        {
          "group": "rhino",
          "module": "js",
          "version": {
            "requires": "1.7R2"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.9"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "17.0"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "1.3.9"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.2.4"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.6.13"
          },
          "reason": "fixes duplicate mod errors in java 17 configurations using old gtnhlib"
        }
      ],
      "files": [
        {
          "name": "worldedit-gtnh-v0.0.8-dev.jar",
          "url": "worldedit-gtnh-v0.0.8-dev.jar",
          "size": 1402883,
          "sha512": "a00990c90f11174c8a271f508907f319731765ec4de146a720148c5b46397c16d5ea4436442e47e0575594bc9325238f39d4122aaaa272d2192b9aa690b7cf3b",
          "sha256": "c4e7d10bb9827cf37e2cfcadbddaa91165b51f3e85ae56bdcec80b18fca79b60",
          "sha1": "d6d04ccd871242e7556b015798ce7692e4d9601c",
          "md5": "0b61c3ad1828cc99b704583176633d06"
        }
      ]
    },
    {
      "name": "reobfElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "srg",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "worldedit-gtnh-v0.0.8.jar",
          "url": "worldedit-gtnh-v0.0.8.jar",
          "size": 1420981,
          "sha512": "fd70aa097ebac81eb8f3e96f0434db2903ef8d9630d964f95dcebfa465dfce55d3298d44780455136e2131ceff5e75f9ac65f459ad1a2a8306f16e2706968c05",
          "sha256": "5e82256fce027435a89389026fd9cb52c28b0ff1da6c3a968af2ff94e2d0891b",
          "sha1": "70c57bc2751d14a089987d529f1627b95993ce91",
          "md5": "9676fe934690893bf4ef1b36ca810d72"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "worldedit-gtnh-v0.0.8-sources.jar",
          "url": "worldedit-gtnh-v0.0.8-sources.jar",
          "size": 1053608,
          "sha512": "6df6d86a9884f41155bc313898310c764aeed85193e2c243f13a46c96a532e7d439e2313abd05d99e694069d9fdba70f080e0a99d1fb45d71d2c38b6b45dcf96",
          "sha256": "119d1e3dfc2085fd37a927a49e70a1f0c88f5582add2b7228aba6c7173c33194",
          "sha1": "471ef4fe912d8e69270c5c73e851e3d643a990d4",
          "md5": "692717b43ce26afb078554a53cda301d"
        }
      ]
    }
  ]
}
