{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GTNewHorizons",
    "module": "Angelica",
    "version": "1.0.0-beta56",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.6.39"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "GTNHLib",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        }
      ],
      "files": [
        {
          "name": "Angelica-1.0.0-beta56-dev.jar",
          "url": "Angelica-1.0.0-beta56-dev.jar",
          "size": 3349904,
          "sha512": "dc794aa5b59ac2bb2e77979bbd0ca31076d4fe8d50a89a2ad3c87ae1ef73ea6fc1297ae7612e634ad4fa52fc772215ff465a36742df03300ff7307593b2e0920",
          "sha256": "b97641dddbb2d80f6f032b63bd3ec4329e522f1c7ff68e1d996cc9596c80afa1",
          "sha1": "4255af7e7a2389330da9461d2bb31c6d50769315",
          "md5": "c344d44956a83a978f3543a679783f07"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.legacymoddingmc",
          "module": "unimixins",
          "version": {
            "requires": "0.1.22"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "unimixins",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.6.39"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "GTNHLib",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.6.37"
          },
          "reason": "fixes duplicate mod errors in java 17 configurations using old gtnhlib"
        }
      ],
      "files": [
        {
          "name": "Angelica-1.0.0-beta56-dev.jar",
          "url": "Angelica-1.0.0-beta56-dev.jar",
          "size": 3349904,
          "sha512": "dc794aa5b59ac2bb2e77979bbd0ca31076d4fe8d50a89a2ad3c87ae1ef73ea6fc1297ae7612e634ad4fa52fc772215ff465a36742df03300ff7307593b2e0920",
          "sha256": "b97641dddbb2d80f6f032b63bd3ec4329e522f1c7ff68e1d996cc9596c80afa1",
          "sha1": "4255af7e7a2389330da9461d2bb31c6d50769315",
          "md5": "c344d44956a83a978f3543a679783f07"
        }
      ]
    },
    {
      "name": "reobfElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "srg",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Angelica-1.0.0-beta56.jar",
          "url": "Angelica-1.0.0-beta56.jar",
          "size": 3395111,
          "sha512": "6295832a9d3efea63e7f40a07254c2fe31d2456dc7e2e28fbc0256ecf9fa3f12f8c478d72972bbe8ce9cf6afd2dd70618ad39872579c24fc2baaf9e6c755b693",
          "sha256": "0e555df7b02c38c72dd1ab37a215ad6345cc32f6287078c5cd1f859014975fb7",
          "sha1": "da3a3ec05c9ffc48c3a0ab1a170fc9f347e8d53a",
          "md5": "bc918ade27663075dc3ed0ab9c086a4e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Angelica-1.0.0-beta56-sources.jar",
          "url": "Angelica-1.0.0-beta56-sources.jar",
          "size": 1421403,
          "sha512": "e665ee5f5528cc171b511e37829a3c8cc4c7c874f89785b563da00c6afe735b6d7f8045862910d91aaa31d82301c958da71e5741e81c169e28bd319fd5f19c69",
          "sha256": "9a1be91d9e0edd5d301d754a79bbd41857c268cb555eec14273ea40987da7736",
          "sha1": "054066cfe32a2f72c81512d8adc7e1642badaba2",
          "md5": "6c75bab41f06fadf413ba549436baee4"
        }
      ]
    }
  ]
}
