{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GTNewHorizons",
    "module": "Postea",
    "version": "1.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.6.37"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "GTNHLib",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        }
      ],
      "files": [
        {
          "name": "Postea-1.1.3-dev.jar",
          "url": "Postea-1.1.3-dev.jar",
          "size": 29500,
          "sha512": "6f4e8e0fbf6d9c35f5e7072baf8ee0387b92f81388308339dcb9cdbf970499541e7f5879d2cf3525780bd5847403ac26bd85523371b5ce07c5de99450eb0f31d",
          "sha256": "e6b6c6e63d45c2f2111547c0c8170ee64bfaefdac284495ff7735458b54bd1d6",
          "sha1": "9e9837306133923cbeb466a23baf4837e6ec1025",
          "md5": "08500c664d09d28ffa6094618328da01"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.legacymoddingmc",
          "module": "unimixins",
          "version": {
            "requires": "0.1.22"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "unimixins",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.6.37"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "GTNHLib",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.6.37"
          },
          "reason": "fixes duplicate mod errors in java 17 configurations using old gtnhlib"
        }
      ],
      "files": [
        {
          "name": "Postea-1.1.3-dev.jar",
          "url": "Postea-1.1.3-dev.jar",
          "size": 29500,
          "sha512": "6f4e8e0fbf6d9c35f5e7072baf8ee0387b92f81388308339dcb9cdbf970499541e7f5879d2cf3525780bd5847403ac26bd85523371b5ce07c5de99450eb0f31d",
          "sha256": "e6b6c6e63d45c2f2111547c0c8170ee64bfaefdac284495ff7735458b54bd1d6",
          "sha1": "9e9837306133923cbeb466a23baf4837e6ec1025",
          "md5": "08500c664d09d28ffa6094618328da01"
        }
      ]
    },
    {
      "name": "reobfElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "srg",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Postea-1.1.3.jar",
          "url": "Postea-1.1.3.jar",
          "size": 30075,
          "sha512": "b982edbfce3cf9036c6abd7f394c2015d744225d5c830a1ca4fecf7f60a76a6c52aad5924a61be15ba1c86f0e979450a8a52f015ece5ebf1c3e94a4e9389f90b",
          "sha256": "605c6086a8984beec112e12525f2dbde4863924a9f7169e23f67d9b95e213c16",
          "sha1": "63fe89ac3ff1217e37b62fa6d68641bdeec3536a",
          "md5": "3bc30511bf0856a453e6008455d33283"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Postea-1.1.3-sources.jar",
          "url": "Postea-1.1.3-sources.jar",
          "size": 15327,
          "sha512": "11cc3aa7fe58744cc920b2ca035b8a3ef66bd6d695db9abcb4f8d96f17cdbf7fe9c9f4f1c04ce8fc11ebb09799b20b7e7c8b004b3dae8c77af992090fc305c64",
          "sha256": "4f6f1061446e99c169e9f2334674e54e1ab2672b7d803b0d58e6f45a084299d3",
          "sha1": "4d36ef6182839b5f7624d74d158db51b7a9e03a6",
          "md5": "715d0f6579bee2cb0f7e2b6f61fe12d3"
        }
      ]
    }
  ]
}
