{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains",
    "module": "annotations",
    "version": "25.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "annotations-25.0.0-common.jar",
          "url": "annotations-25.0.0-common.jar",
          "size": 13087,
          "sha512": "fa66dbe95bf36eb3c106e3fd68b3dc26705cb6ef6f08b987019822cf4c79224a9bc871d16db656441ca1cc7fa0a3f7e5862f1f1a2a1c3d2a1d7ac2a13d842f33",
          "sha256": "4b3394afd8360812afe877913bcb94e8a93449a6b671e6afef4690186a841d31",
          "sha1": "afc307e9cc3fdb492a7c05dd9ac0970f7569db4c",
          "md5": "3d45da8cf0bd3c53b35fcfbabb9068f6"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "annotations-25.0.0-sources-common.jar",
          "url": "annotations-25.0.0-sources-common.jar",
          "size": 53708,
          "sha512": "bf47c0e54b48ca1199e7854065e054b50027707d6e05362465832634f1b5428de4074cdcb5f196e5601cd6e3799d400a12b435380fbaf36c7a686eb35030a1c4",
          "sha256": "e566d0a1158a85b7bed4d9bc1132b9f46c4d43b10aa4dc5b24160e4177e4e7e3",
          "sha1": "d9574aa22169cde048c2bd8e0a661bb2b4cbb007",
          "md5": "aec383549e099548358930d28708e0bb"
        }
      ]
    },
    {
      "name": "jvmApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotations-25.0.0.jar",
          "url": "annotations-25.0.0.jar",
          "size": 30721,
          "sha512": "27d909940c188b8269dbbb46bf711f3b644efe2613e0ce933883ee736f0294f67815c0a4782a922beff9ed3912f81f799251a991cbb7767a09109ba439b39253",
          "sha256": "9c0a1528240d1f732bfeac182e126e76ead2e6dfa157f1ad8e3c891b19281538",
          "sha1": "c1e6b966db352094ac3bf7f88f3bdef332fe43f0",
          "md5": "07f6ac421f361ecd170c6bab6a7085c6"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotations-25.0.0.jar",
          "url": "annotations-25.0.0.jar",
          "size": 30721,
          "sha512": "27d909940c188b8269dbbb46bf711f3b644efe2613e0ce933883ee736f0294f67815c0a4782a922beff9ed3912f81f799251a991cbb7767a09109ba439b39253",
          "sha256": "9c0a1528240d1f732bfeac182e126e76ead2e6dfa157f1ad8e3c891b19281538",
          "sha1": "c1e6b966db352094ac3bf7f88f3bdef332fe43f0",
          "md5": "07f6ac421f361ecd170c6bab6a7085c6"
        }
      ]
    },
    {
      "name": "jvmSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "annotations-25.0.0-sources.jar",
          "url": "annotations-25.0.0-sources.jar",
          "size": 65462,
          "sha512": "d24e3a752fe0a9913a049c82ff6b0b3c8b545bdc896c368e0381b921febb075660d5029691a05f4baabba20318a99408af5625723b6516c560df00a9d15138a5",
          "sha256": "92185b610128c59d99adbd6c27e5efd893422582b2f887cdd0415d25b1246d1d",
          "sha1": "64af7d00c1e23d847a7dbfe874f7eafe1e4595d7",
          "md5": "cb0073e9da0eefd7ba442a46fa2749ca"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "annotations-25.0.0-javadoc.jar",
          "url": "annotations-25.0.0-javadoc.jar",
          "size": 146496,
          "sha512": "379c3c35ec00895962f1b2384b46b8254fb9d64833ae248bf73178d7f8d4b9a4e3a971c0ea16c4fe50c77229c8de22ff714a249c6c6a7f0958eec52717734801",
          "sha256": "13ac2606d53c5931d75df1b856c6df3d4e5cbd7b8f368233d96bf7407ec6a6ca",
          "sha1": "bcd9135bafbefc373a1e637fedad55ea85d3c339",
          "md5": "6efe7acdc007351e7f7a0270f2fc2cd9"
        }
      ]
    },
    {
      "name": "androidNativeArm32ApiElements",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotations-androidNativeArm32/25.0.0/annotations-androidNativeArm32-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-androidNativeArm32",
        "version": "25.0.0"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotations-androidNativeArm32/25.0.0/annotations-androidNativeArm32-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-androidNativeArm32",
        "version": "25.0.0"
      }
    },
    {
      "name": "androidNativeArm64ApiElements",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotations-androidNativeArm64/25.0.0/annotations-androidNativeArm64-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-androidNativeArm64",
        "version": "25.0.0"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotations-androidNativeArm64/25.0.0/annotations-androidNativeArm64-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-androidNativeArm64",
        "version": "25.0.0"
      }
    },
    {
      "name": "androidNativeX64ApiElements",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotations-androidNativeX64/25.0.0/annotations-androidNativeX64-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-androidNativeX64",
        "version": "25.0.0"
      }
    },
    {
      "name": "androidNativeX64SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotations-androidNativeX64/25.0.0/annotations-androidNativeX64-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-androidNativeX64",
        "version": "25.0.0"
      }
    },
    {
      "name": "androidNativeX86ApiElements",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotations-androidNativeX86/25.0.0/annotations-androidNativeX86-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-androidNativeX86",
        "version": "25.0.0"
      }
    },
    {
      "name": "androidNativeX86SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotations-androidNativeX86/25.0.0/annotations-androidNativeX86-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-androidNativeX86",
        "version": "25.0.0"
      }
    },
    {
      "name": "iosArm64ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotations-iosArm64/25.0.0/annotations-iosArm64-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-iosArm64",
        "version": "25.0.0"
      }
    },
    {
      "name": "iosArm64SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotations-iosArm64/25.0.0/annotations-iosArm64-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-iosArm64",
        "version": "25.0.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotations-iosSimulatorArm64/25.0.0/annotations-iosSimulatorArm64-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-iosSimulatorArm64",
        "version": "25.0.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotations-iosSimulatorArm64/25.0.0/annotations-iosSimulatorArm64-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-iosSimulatorArm64",
        "version": "25.0.0"
      }
    },
    {
      "name": "iosX64ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotations-iosX64/25.0.0/annotations-iosX64-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-iosX64",
        "version": "25.0.0"
      }
    },
    {
      "name": "iosX64SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotations-iosX64/25.0.0/annotations-iosX64-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-iosX64",
        "version": "25.0.0"
      }
    },
    {
      "name": "jsApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../annotations-js/25.0.0/annotations-js-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-js",
        "version": "25.0.0"
      }
    },
    {
      "name": "jsRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../annotations-js/25.0.0/annotations-js-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-js",
        "version": "25.0.0"
      }
    },
    {
      "name": "jsSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../annotations-js/25.0.0/annotations-js-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-js",
        "version": "25.0.0"
      }
    },
    {
      "name": "linuxArm64ApiElements",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotations-linuxArm64/25.0.0/annotations-linuxArm64-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-linuxArm64",
        "version": "25.0.0"
      }
    },
    {
      "name": "linuxArm64SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotations-linuxArm64/25.0.0/annotations-linuxArm64-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-linuxArm64",
        "version": "25.0.0"
      }
    },
    {
      "name": "linuxX64ApiElements",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotations-linuxX64/25.0.0/annotations-linuxX64-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-linuxX64",
        "version": "25.0.0"
      }
    },
    {
      "name": "linuxX64SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotations-linuxX64/25.0.0/annotations-linuxX64-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-linuxX64",
        "version": "25.0.0"
      }
    },
    {
      "name": "macosArm64ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotations-macosArm64/25.0.0/annotations-macosArm64-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-macosArm64",
        "version": "25.0.0"
      }
    },
    {
      "name": "macosArm64SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotations-macosArm64/25.0.0/annotations-macosArm64-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-macosArm64",
        "version": "25.0.0"
      }
    },
    {
      "name": "macosX64ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotations-macosX64/25.0.0/annotations-macosX64-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-macosX64",
        "version": "25.0.0"
      }
    },
    {
      "name": "macosX64SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotations-macosX64/25.0.0/annotations-macosX64-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-macosX64",
        "version": "25.0.0"
      }
    },
    {
      "name": "mingwX64ApiElements",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotations-mingwX64/25.0.0/annotations-mingwX64-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-mingwX64",
        "version": "25.0.0"
      }
    },
    {
      "name": "mingwX64SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotations-mingwX64/25.0.0/annotations-mingwX64-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-mingwX64",
        "version": "25.0.0"
      }
    },
    {
      "name": "tvosArm64ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotations-tvosArm64/25.0.0/annotations-tvosArm64-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-tvosArm64",
        "version": "25.0.0"
      }
    },
    {
      "name": "tvosArm64SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotations-tvosArm64/25.0.0/annotations-tvosArm64-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-tvosArm64",
        "version": "25.0.0"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotations-tvosSimulatorArm64/25.0.0/annotations-tvosSimulatorArm64-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-tvosSimulatorArm64",
        "version": "25.0.0"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotations-tvosSimulatorArm64/25.0.0/annotations-tvosSimulatorArm64-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-tvosSimulatorArm64",
        "version": "25.0.0"
      }
    },
    {
      "name": "tvosX64ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotations-tvosX64/25.0.0/annotations-tvosX64-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-tvosX64",
        "version": "25.0.0"
      }
    },
    {
      "name": "tvosX64SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotations-tvosX64/25.0.0/annotations-tvosX64-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-tvosX64",
        "version": "25.0.0"
      }
    },
    {
      "name": "wasmJsApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../annotations-wasmJs/25.0.0/annotations-wasmJs-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-wasmJs",
        "version": "25.0.0"
      }
    },
    {
      "name": "wasmJsRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../annotations-wasmJs/25.0.0/annotations-wasmJs-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-wasmJs",
        "version": "25.0.0"
      }
    },
    {
      "name": "wasmJsSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../annotations-wasmJs/25.0.0/annotations-wasmJs-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-wasmJs",
        "version": "25.0.0"
      }
    },
    {
      "name": "wasmWasiApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../annotations-wasmWasi/25.0.0/annotations-wasmWasi-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-wasmWasi",
        "version": "25.0.0"
      }
    },
    {
      "name": "wasmWasiRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../annotations-wasmWasi/25.0.0/annotations-wasmWasi-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-wasmWasi",
        "version": "25.0.0"
      }
    },
    {
      "name": "wasmWasiSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../annotations-wasmWasi/25.0.0/annotations-wasmWasi-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-wasmWasi",
        "version": "25.0.0"
      }
    },
    {
      "name": "watchosArm32ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotations-watchosArm32/25.0.0/annotations-watchosArm32-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-watchosArm32",
        "version": "25.0.0"
      }
    },
    {
      "name": "watchosArm32SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotations-watchosArm32/25.0.0/annotations-watchosArm32-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-watchosArm32",
        "version": "25.0.0"
      }
    },
    {
      "name": "watchosArm64ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotations-watchosArm64/25.0.0/annotations-watchosArm64-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-watchosArm64",
        "version": "25.0.0"
      }
    },
    {
      "name": "watchosArm64SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotations-watchosArm64/25.0.0/annotations-watchosArm64-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-watchosArm64",
        "version": "25.0.0"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotations-watchosDeviceArm64/25.0.0/annotations-watchosDeviceArm64-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-watchosDeviceArm64",
        "version": "25.0.0"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotations-watchosDeviceArm64/25.0.0/annotations-watchosDeviceArm64-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-watchosDeviceArm64",
        "version": "25.0.0"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotations-watchosSimulatorArm64/25.0.0/annotations-watchosSimulatorArm64-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-watchosSimulatorArm64",
        "version": "25.0.0"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotations-watchosSimulatorArm64/25.0.0/annotations-watchosSimulatorArm64-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-watchosSimulatorArm64",
        "version": "25.0.0"
      }
    },
    {
      "name": "watchosX64ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotations-watchosX64/25.0.0/annotations-watchosX64-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-watchosX64",
        "version": "25.0.0"
      }
    },
    {
      "name": "watchosX64SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../annotations-watchosX64/25.0.0/annotations-watchosX64-25.0.0.module",
        "group": "org.jetbrains",
        "module": "annotations-watchosX64",
        "version": "25.0.0"
      }
    }
  ]
}
