{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GTNewHorizons",
    "module": "ForgeMultipart",
    "version": "1.6.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ForgeMultipart-1.6.8-dev.jar",
          "url": "ForgeMultipart-1.6.8-dev.jar",
          "size": 933218,
          "sha512": "d1785958579de0e991849afb90db1d90de40bf42f63bd495d7bd5e24dc98902304b9643db24e7cc25fdaf0f718d0d04bd5eaf925703dcc2dcb5abcb15ef76394",
          "sha256": "dde8a196a7bc062b424dcdce7fe3d695598ee60fcc48cef50343699dec6ff1ac",
          "sha1": "e27ee2c7daa85957b66c9518d10dae4c5e4a810d",
          "md5": "c18647011c1a1bcfdd8d6453fc232f1b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "CodeChickenCore",
          "version": {
            "requires": "1.4.3"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "CodeChickenCore",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.6.37"
          },
          "reason": "fixes duplicate mod errors in java 17 configurations using old gtnhlib"
        }
      ],
      "files": [
        {
          "name": "ForgeMultipart-1.6.8-dev.jar",
          "url": "ForgeMultipart-1.6.8-dev.jar",
          "size": 933218,
          "sha512": "d1785958579de0e991849afb90db1d90de40bf42f63bd495d7bd5e24dc98902304b9643db24e7cc25fdaf0f718d0d04bd5eaf925703dcc2dcb5abcb15ef76394",
          "sha256": "dde8a196a7bc062b424dcdce7fe3d695598ee60fcc48cef50343699dec6ff1ac",
          "sha1": "e27ee2c7daa85957b66c9518d10dae4c5e4a810d",
          "md5": "c18647011c1a1bcfdd8d6453fc232f1b"
        }
      ]
    },
    {
      "name": "reobfElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "srg",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ForgeMultipart-1.6.8.jar",
          "url": "ForgeMultipart-1.6.8.jar",
          "size": 943646,
          "sha512": "79e54b9c4cf0f9bee2e186736cb8a7b906c604d92d81b5aca5d409d19eb4184a2ad340de458c2edafae9eebf5c89bafb023d85c397ff5b69284b0afe8b6a78da",
          "sha256": "7e2907bc37885bb4b523f1fe4dc1938acd0fc1a0a94349d64d68c9561a38f191",
          "sha1": "8988c3baa18e5541027c0bc905cccd32aba83364",
          "md5": "7da5de3367a1e5280a142be7244ecb38"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ForgeMultipart-1.6.8-sources.jar",
          "url": "ForgeMultipart-1.6.8-sources.jar",
          "size": 149353,
          "sha512": "e5bdb9c2a013739ea8cd690860bdc42c1865d0f5fb531fbc2c8482bcd6a2da7007b81f4d68efbd536b4dc4a0983012f4ce4d290dbda3efd2cef348e7db9837d4",
          "sha256": "d80e183096ae6287b93f8f809deb04bd9edbba339a240ae9cb0e56507459c2f8",
          "sha1": "e0b8b38027b16021f8e53c9619ae7dd4c65c1660",
          "md5": "8cc885889cd69d2712a4cb521aaffb4c"
        }
      ]
    }
  ]
}
