{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GTNewHorizons",
    "module": "Navigator",
    "version": "1.0.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.6.37"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "GTNHLib",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "25.0.0"
          }
        },
        {
          "group": "maven.modrinth",
          "module": "journeymap",
          "version": {
            "requires": "5.2.9"
          }
        }
      ],
      "files": [
        {
          "name": "Navigator-1.0.17-dev.jar",
          "url": "Navigator-1.0.17-dev.jar",
          "size": 108761,
          "sha512": "d7bf1950b10ac398361a16d5555fb18408e60e61fec3d393c64508724ab807c97883c46c9d79ebdd239a66999b4b5dcab00509112c82763a769818107607d9a0",
          "sha256": "3d01517bd2c4e418469646fc80af99d851efda9e75da6d75951d120b6e8400c5",
          "sha1": "50cf10faf9e96806dc597590259c40fbc3717a5b",
          "md5": "e4f5fd2433b4fc94d25cfb017a4036a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.legacymoddingmc",
          "module": "unimixins",
          "version": {
            "requires": "0.1.22"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "unimixins",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.6.37"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "GTNHLib",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.6.13"
          },
          "reason": "fixes duplicate mod errors in java 17 configurations using old gtnhlib"
        }
      ],
      "files": [
        {
          "name": "Navigator-1.0.17-dev.jar",
          "url": "Navigator-1.0.17-dev.jar",
          "size": 108761,
          "sha512": "d7bf1950b10ac398361a16d5555fb18408e60e61fec3d393c64508724ab807c97883c46c9d79ebdd239a66999b4b5dcab00509112c82763a769818107607d9a0",
          "sha256": "3d01517bd2c4e418469646fc80af99d851efda9e75da6d75951d120b6e8400c5",
          "sha1": "50cf10faf9e96806dc597590259c40fbc3717a5b",
          "md5": "e4f5fd2433b4fc94d25cfb017a4036a4"
        }
      ]
    },
    {
      "name": "reobfElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "srg",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Navigator-1.0.17.jar",
          "url": "Navigator-1.0.17.jar",
          "size": 110203,
          "sha512": "54eead5df97cf8d143cbf8441776a030f4a5034443c1a3e428abbc911a9b5690f575fd892e56e006c7406f7ac2a21fcf6571b754a453c93e5883bb6286ab2bcb",
          "sha256": "951b6311ade2cafd1bef2f40862152965e79689e9cf9c8a9517ca837c5022998",
          "sha1": "cf8fa0a428887aa35d5f67b7bd7d586ecbd073f4",
          "md5": "307fb42e66ea7021f60fbe1e36372ec4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Navigator-1.0.17-sources.jar",
          "url": "Navigator-1.0.17-sources.jar",
          "size": 64827,
          "sha512": "f7d9b12eb69615035d252d7a101f13e8ff2ec3386019b2618dbe282d7dac559c8e3a8597687ae63266697d93a0d0a12a62042b6c5f3a4dc7ccc70320b0cb4173",
          "sha256": "9077cc846f5ab34b4f2839c4366f4e896d51fb932d4933204d4ac444af7de14c",
          "sha1": "0ba10b5abc219a2dbd8daf34c64edd05b11c30cf",
          "md5": "d7210b4c9b470de1a9403168d8322c51"
        }
      ]
    }
  ]
}
