{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GTNewHorizons",
    "module": "Galaxy-Space-GTNH",
    "version": "1.1.121-GTNH",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "Galacticraft",
          "version": {
            "requires": "3.3.12-GTNH"
          },
          "excludes": [
            {
              "group": "com.github.GTNewHorizons",
              "module": "GT5-Unofficial"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "Galacticraft",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "NotEnoughItems",
          "version": {
            "requires": "2.7.80-GTNH"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "NotEnoughItems",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        }
      ],
      "files": [
        {
          "name": "Galaxy-Space-GTNH-1.1.121-GTNH-dev.jar",
          "url": "Galaxy-Space-GTNH-1.1.121-GTNH-dev.jar",
          "size": 8024776,
          "sha512": "cbc78c3d68976555b97937e1be4425560868267d9ea6036af4b51b787d4694d039ad1b1aab59b2950e1a1749561dfa3a8cbac7ba0caac32b18aaf1417a14edc1",
          "sha256": "a06488ee8cb1deb2ed87585778a791857f8f35b5555155a1f4bfb156d27f70e4",
          "sha1": "8fe9b335b7514ed901e8d6d399afc0293886ed13",
          "md5": "1941b88ebad6fc40fec75f5563476e42"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "Galacticraft",
          "version": {
            "requires": "3.3.12-GTNH"
          },
          "excludes": [
            {
              "group": "com.github.GTNewHorizons",
              "module": "GT5-Unofficial"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "Galacticraft",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "NotEnoughItems",
          "version": {
            "requires": "2.7.80-GTNH"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "NotEnoughItems",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.6.37"
          },
          "reason": "fixes duplicate mod errors in java 17 configurations using old gtnhlib"
        }
      ],
      "files": [
        {
          "name": "Galaxy-Space-GTNH-1.1.121-GTNH-dev.jar",
          "url": "Galaxy-Space-GTNH-1.1.121-GTNH-dev.jar",
          "size": 8024776,
          "sha512": "cbc78c3d68976555b97937e1be4425560868267d9ea6036af4b51b787d4694d039ad1b1aab59b2950e1a1749561dfa3a8cbac7ba0caac32b18aaf1417a14edc1",
          "sha256": "a06488ee8cb1deb2ed87585778a791857f8f35b5555155a1f4bfb156d27f70e4",
          "sha1": "8fe9b335b7514ed901e8d6d399afc0293886ed13",
          "md5": "1941b88ebad6fc40fec75f5563476e42"
        }
      ]
    },
    {
      "name": "reobfElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "srg",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Galaxy-Space-GTNH-1.1.121-GTNH.jar",
          "url": "Galaxy-Space-GTNH-1.1.121-GTNH.jar",
          "size": 8041494,
          "sha512": "9fa2a526aa6a6f187da662124687daaceb2e83c10ec3a12bae0944904f59d8894e0e8e341762bf780aec498fb0baf9279e27a56b081bfb1cd0859478b7e548b6",
          "sha256": "bb0ccf7f54cd73cee83ea8a8ce9e63e1d20ba754a5fb4ebb342d1e81498b7ca8",
          "sha1": "69ee051c61fa1ad5219ef7d47150e110b92f765e",
          "md5": "e3e907e8d3036a068e0df19a12d14e77"
        }
      ]
    }
  ]
}
