{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.gmazzo.buildconfig",
    "module": "plugin",
    "version": "5.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-5.7.1.jar",
          "url": "plugin-5.7.1.jar",
          "size": 155919,
          "sha512": "d06b6cb5af8d6b5569f6cc6b8985c669003f6dd1af530c4ed9919dc525c59fbc5b4af64e7925c48019232f7022f14c19d5f398d57980dce8f9587a145d155f53",
          "sha256": "f8597e76cb50e9bb117b12a9bb5540153911716546dfc076084f4547e69f56c5",
          "sha1": "b9f10f15dd754709a104c0e292e68cb589db190c",
          "md5": "a6c1341e3f06835696508942ecaf5aad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-5.7.1.jar",
          "url": "plugin-5.7.1.jar",
          "size": 155919,
          "sha512": "d06b6cb5af8d6b5569f6cc6b8985c669003f6dd1af530c4ed9919dc525c59fbc5b4af64e7925c48019232f7022f14c19d5f398d57980dce8f9587a145d155f53",
          "sha256": "f8597e76cb50e9bb117b12a9bb5540153911716546dfc076084f4547e69f56c5",
          "sha1": "b9f10f15dd754709a104c0e292e68cb589db190c",
          "md5": "a6c1341e3f06835696508942ecaf5aad"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "plugin-5.7.1-javadoc.jar",
          "url": "plugin-5.7.1-javadoc.jar",
          "size": 499361,
          "sha512": "f13da3e071f2dd22bcb4e945994875e167abe3f44efd04cab49d894eaec2f4afde90c3d117bd85fd8b84b50ea57d8b71b764ea0874010823b554721a2d488a65",
          "sha256": "30133d9bea4b14412f3cc6404e7d2bb55cdafa045a1f7fb14352bfa8ffc3ec48",
          "sha1": "1276f614ec1f76cf307df30ac870cdaeed87fd84",
          "md5": "589c82ec5f3027efb8e6eacf4f122ca9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "plugin-5.7.1-sources.jar",
          "url": "plugin-5.7.1-sources.jar",
          "size": 23505,
          "sha512": "4ed4ad59f99b09d7d7faebea05f808d3410f3144a608f530376074495c6f537a02c7052618ef1751999decf794ded5c18a4ec44ecc9929f9dbc00b5aa893bdfe",
          "sha256": "729e49bd331f45d8181cde0152daa39807938079114d09d63e39c5655598839c",
          "sha1": "c59ad6b073394435103d1b44192a4b561a6a0a66",
          "md5": "b9dc962b427cf3c3a0b0958dbe11edea"
        }
      ]
    }
  ]
}
