{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GTNewHorizons",
    "module": "ModularUI2",
    "version": "2.2.18-1.7.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.6.39"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "GTNHLib",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ModularUI2-2.2.18-1.7.10-dev.jar",
          "url": "ModularUI2-2.2.18-1.7.10-dev.jar",
          "size": 1678417,
          "sha512": "262fd7d33726fe2f320d2acc266f8877c39ca60741962f4b18ad7dc29093d414c7403f8b085cefae317d31fe365b9f49719a7ccd6081021a58a7937a08c2c941",
          "sha256": "d79af9d6dad2e6fbc9a195cd1e04ebbde0c2cf9a536400111612aa8c4d1c3043",
          "sha1": "f7ff83c698e5bbfb23725a8cbb36fca6876610af",
          "md5": "4b54d7d9eacc6b55367ad385c8d57dc2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.legacymoddingmc",
          "module": "unimixins",
          "version": {
            "requires": "0.1.23"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "unimixins",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "NotEnoughItems",
          "version": {
            "requires": "2.7.79-GTNH"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "NotEnoughItems",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "Baubles-Expanded",
          "version": {
            "requires": "2.1.13-GTNH"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "Baubles-Expanded",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.6.39"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "GTNHLib",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.6.37"
          },
          "reason": "fixes duplicate mod errors in java 17 configurations using old gtnhlib"
        }
      ],
      "files": [
        {
          "name": "ModularUI2-2.2.18-1.7.10-dev.jar",
          "url": "ModularUI2-2.2.18-1.7.10-dev.jar",
          "size": 1678417,
          "sha512": "262fd7d33726fe2f320d2acc266f8877c39ca60741962f4b18ad7dc29093d414c7403f8b085cefae317d31fe365b9f49719a7ccd6081021a58a7937a08c2c941",
          "sha256": "d79af9d6dad2e6fbc9a195cd1e04ebbde0c2cf9a536400111612aa8c4d1c3043",
          "sha1": "f7ff83c698e5bbfb23725a8cbb36fca6876610af",
          "md5": "4b54d7d9eacc6b55367ad385c8d57dc2"
        }
      ]
    },
    {
      "name": "reobfElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "srg",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ModularUI2-2.2.18-1.7.10.jar",
          "url": "ModularUI2-2.2.18-1.7.10.jar",
          "size": 1692017,
          "sha512": "9eb9a9ee1ba85b7fdb61cb1e94a8db2cbd7e9b58dbdc721f40da96b1a286559e9cae6dbfc62332fa513a368735cb005c093fa50c5dc6c52d60e57588b7d0b819",
          "sha256": "0b993a752a1ba8bb9ec2637d9027a4b812e6a1217aec03f3baeb7af43e672fa7",
          "sha1": "6baceb564c23cc5f6e6fa2b8c7130bc202333821",
          "md5": "61bb8ca0af783d4f89590026b110b9e7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ModularUI2-2.2.18-1.7.10-sources.jar",
          "url": "ModularUI2-2.2.18-1.7.10-sources.jar",
          "size": 607256,
          "sha512": "982e0000e78f494e8dbe8afcdab56460cacfe9b3f9d156609702c7e9352b54943b3e9b60ed8edde96f06d535bbc1d1b5a7364a661ed1404f43241a47bf1b3a12",
          "sha256": "e2dc58090e94f69c7309d4641f94efa060bf72e624ee4a688342dc9b1b680dd3",
          "sha1": "3e03e00e8cdde152ebf0a2da9160d73d2e3e2dac",
          "md5": "a5f179581c01b5bd2d3465d23fafec17"
        }
      ]
    }
  ]
}
