{
  "formatVersion": "1.1",
  "component": {
    "group": "me.eigenraven.java8unsupported",
    "module": "java-8-unsupported-shim",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "java-8-unsupported-shim-1.0.0.jar",
          "url": "java-8-unsupported-shim-1.0.0.jar",
          "size": 10139,
          "sha512": "13272c881e8704d8e8df5418c5a70f1f1c70315459c870efc6ed1ae0a819cafd104c60f49ca51ff4d7de16774ce8ae73355f0207d84ef481ac255af5ed2501a7",
          "sha256": "a5c607528c6372effa12af76bbeb78e1735a0aedeaff2eeb1210e0b6dbb225cd",
          "sha1": "2d0687782e2d091a6f3cf4709c54368fe6ab47e8",
          "md5": "4b4a0fb0102d002f6c91729af4ae7bba"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "java-8-unsupported-shim-1.0.0.jar",
          "url": "java-8-unsupported-shim-1.0.0.jar",
          "size": 10139,
          "sha512": "13272c881e8704d8e8df5418c5a70f1f1c70315459c870efc6ed1ae0a819cafd104c60f49ca51ff4d7de16774ce8ae73355f0207d84ef481ac255af5ed2501a7",
          "sha256": "a5c607528c6372effa12af76bbeb78e1735a0aedeaff2eeb1210e0b6dbb225cd",
          "sha1": "2d0687782e2d091a6f3cf4709c54368fe6ab47e8",
          "md5": "4b4a0fb0102d002f6c91729af4ae7bba"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "java-8-unsupported-shim-1.0.0-sources.jar",
          "url": "java-8-unsupported-shim-1.0.0-sources.jar",
          "size": 5412,
          "sha512": "1e33292c11212900757072f18100df61d292ced78af78571cf42ca1a12c5945029e76ef937acd74e59a79e82e79aeecc1448fc63048c2982408ca77541a628a2",
          "sha256": "dd6895eab25673471d70e68165e2da44ef021691fb301e400ecfab64a32a24f4",
          "sha1": "8fbb364e5f07814502c654e8720ece733a0c08d2",
          "md5": "4c811ea9237c3ffb4eae410f6ff47a50"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "java-8-unsupported-shim-1.0.0-javadoc.jar",
          "url": "java-8-unsupported-shim-1.0.0-javadoc.jar",
          "size": 61203,
          "sha512": "6720bc03926fa750a5245b795399917b70766aa3a1d3f9e60870352bf9f9caf26b9e480ffb07c0c90763eabfda4dd1de1cebbf2d38fb30ef6f6e2f7850170703",
          "sha256": "5239e6a9c4966863b8cc00d16e680da3e77411fefeac045d93ed5443a1872b06",
          "sha1": "0c007628c9d61a061776296a70732ace9f8806ab",
          "md5": "7a70e9d4ebc6a890cb9f850e956ec369"
        }
      ]
    }
  ]
}
