{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GTNewHorizons",
    "module": "MagicBees",
    "version": "2.9.4-GTNH",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "ForestryMC",
          "version": {
            "requires": "4.10.11"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "ForestryMC",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        }
      ],
      "files": [
        {
          "name": "MagicBees-2.9.4-GTNH-dev.jar",
          "url": "MagicBees-2.9.4-GTNH-dev.jar",
          "size": 1025985,
          "sha512": "9c7931dcccb8e7c0c961d4a533bd3742c48edf43fcff1a56ce2003d97a0397f5f424f8e91c6fa402f74d932dbab71069157c3c23a66cc9d4d429b3be892618fa",
          "sha256": "006a1ef3ee7d7f61922c6c9cf2efeeb930235f7d0f6fe76c31fbc91d7129a3aa",
          "sha1": "58fe6dee137adfd636ce3bc01a07db968fceacbd",
          "md5": "40d11ae2dffba0097cb8b08393da9a74"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "ForestryMC",
          "version": {
            "requires": "4.10.11"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "ForestryMC",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.6.13"
          },
          "reason": "fixes duplicate mod errors in java 17 configurations using old gtnhlib"
        }
      ],
      "files": [
        {
          "name": "MagicBees-2.9.4-GTNH-dev.jar",
          "url": "MagicBees-2.9.4-GTNH-dev.jar",
          "size": 1025985,
          "sha512": "9c7931dcccb8e7c0c961d4a533bd3742c48edf43fcff1a56ce2003d97a0397f5f424f8e91c6fa402f74d932dbab71069157c3c23a66cc9d4d429b3be892618fa",
          "sha256": "006a1ef3ee7d7f61922c6c9cf2efeeb930235f7d0f6fe76c31fbc91d7129a3aa",
          "sha1": "58fe6dee137adfd636ce3bc01a07db968fceacbd",
          "md5": "40d11ae2dffba0097cb8b08393da9a74"
        }
      ]
    },
    {
      "name": "reobfElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "srg",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "MagicBees-2.9.4-GTNH.jar",
          "url": "MagicBees-2.9.4-GTNH.jar",
          "size": 1034867,
          "sha512": "d143e5bcbbe8e639dd2e56f81412947c05ed61675e045a3508d9731ea140f5cb3e791becea78055e085a406beb2df67b9c740b2a0cd115d032fa31a4e98a8684",
          "sha256": "2e17daaf4a987b69610acd496b6107c6e221bfc9373e4fc9cc00c211358c9d17",
          "sha1": "1b685a9fb979506221a1895013896f1a4b41ba29",
          "md5": "5cf1e33e2165bf096611ffad99299dc4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "MagicBees-2.9.4-GTNH-sources.jar",
          "url": "MagicBees-2.9.4-GTNH-sources.jar",
          "size": 812376,
          "sha512": "2f79c14522c2a3b062d6e42b5906e25885c0049867cac6e43557fd5d9c80a6bae41c3e7542308b7241bfe0bb04ff61bb553284272072a4ded08a10983cb519c4",
          "sha256": "a34eb2438f55829593634280186bf4c4a828cb3dd5e19d4cbc0d55fe69e3b1d3",
          "sha1": "34de285cf5da2b45115985e9e35094941ba02629",
          "md5": "a2344e59d57340d545628c05c0f1541d"
        }
      ]
    }
  ]
}
