{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GTNewHorizons",
    "module": "NotEnoughItems",
    "version": "2.7.91-GTNH",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "CodeChickenCore",
          "version": {
            "requires": "1.4.7"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "CodeChickenCore",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.13.2"
          }
        }
      ],
      "files": [
        {
          "name": "NotEnoughItems-2.7.91-GTNH-dev.jar",
          "url": "NotEnoughItems-2.7.91-GTNH-dev.jar",
          "size": 1462037,
          "sha512": "cd4d19f929d2759b3ef6fc0abf19f365b815378a7111deb80ab9d8d825749614150545f7a5026e179366c6714eff1b2f02a1b7b0df14ae0fe6a9c5a8075cae91",
          "sha256": "3360ba66f9fd477f121d7d32b375ae76a9423f4e42d9dc2a8ce35be5a6818c6d",
          "sha1": "5d7f81ef55b3b1a954ed53a14f58d4a0fbd17457",
          "md5": "8d65fb509edfd408bf603a186bf4cfd5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.6.39"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "GTNHLib",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "CodeChickenCore",
          "version": {
            "requires": "1.4.7"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "CodeChickenCore",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "org.antlr",
          "module": "antlr4",
          "version": {
            "requires": "4.13.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.6.37"
          },
          "reason": "fixes duplicate mod errors in java 17 configurations using old gtnhlib"
        }
      ],
      "files": [
        {
          "name": "NotEnoughItems-2.7.91-GTNH-dev.jar",
          "url": "NotEnoughItems-2.7.91-GTNH-dev.jar",
          "size": 1462037,
          "sha512": "cd4d19f929d2759b3ef6fc0abf19f365b815378a7111deb80ab9d8d825749614150545f7a5026e179366c6714eff1b2f02a1b7b0df14ae0fe6a9c5a8075cae91",
          "sha256": "3360ba66f9fd477f121d7d32b375ae76a9423f4e42d9dc2a8ce35be5a6818c6d",
          "sha1": "5d7f81ef55b3b1a954ed53a14f58d4a0fbd17457",
          "md5": "8d65fb509edfd408bf603a186bf4cfd5"
        }
      ]
    },
    {
      "name": "reobfElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "srg",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NotEnoughItems-2.7.91-GTNH.jar",
          "url": "NotEnoughItems-2.7.91-GTNH.jar",
          "size": 1477041,
          "sha512": "bbf599ab786cd3077211e18ac089bf0dc538f2bead9493d584e8582de0bb6a4de3f4354b3d70f23b6cc4b42a2291f0555106e6c0a1c1b6fce6c730df5760a37c",
          "sha256": "809b92054043635eb1da05a25faa1f3c11c3fb67624339c580642680e25162ee",
          "sha1": "6270ae3bd18c4f9205d0d172e2966b402199eb99",
          "md5": "27d0372f45896279cc79a1971fd6a2b1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NotEnoughItems-2.7.91-GTNH-sources.jar",
          "url": "NotEnoughItems-2.7.91-GTNH-sources.jar",
          "size": 542035,
          "sha512": "70f100ff0553a630ea740b6e9f19d819145583cab6557574d4d7b48d02b7a96d9520f1b1a218cc6e2d2d9004e7cb9b3f1ea2139ae5bdb6c17db088eb72b53414",
          "sha256": "4cc0b1b5415c3d833db92e6e1fb9554043407ef1d3c82e048644cf8ce82a849f",
          "sha1": "2fada75d76c1174cc01ca0852e1a4fa0f2101372",
          "md5": "97478a405b912a49cd4ca23703c0119a"
        }
      ]
    }
  ]
}
