{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GTNewHorizons",
    "module": "AppleCore",
    "version": "3.3.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "AppleCore-3.3.7-dev.jar",
          "url": "AppleCore-3.3.7-dev.jar",
          "size": 99530,
          "sha512": "6cf6253a85558b88a3c25d5325c5cdad1013ef66153ad9670cf11806b741eb2dd8c45ed53c8eac5475819fc78200abb53bc8458daf63db24528620499cc8edf8",
          "sha256": "db518386f540b7042cdec829edafbc86c17712138971320f4355eeff27c63e46",
          "sha1": "995288a056b58e83cd43d5d770deeda3d2c37950",
          "md5": "0ad3fe97dfbca1132005e815991e8262"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.legacymoddingmc",
          "module": "unimixins",
          "version": {
            "requires": "0.1.22"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "unimixins",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.6.37"
          },
          "reason": "fixes duplicate mod errors in java 17 configurations using old gtnhlib"
        }
      ],
      "files": [
        {
          "name": "AppleCore-3.3.7-dev.jar",
          "url": "AppleCore-3.3.7-dev.jar",
          "size": 99530,
          "sha512": "6cf6253a85558b88a3c25d5325c5cdad1013ef66153ad9670cf11806b741eb2dd8c45ed53c8eac5475819fc78200abb53bc8458daf63db24528620499cc8edf8",
          "sha256": "db518386f540b7042cdec829edafbc86c17712138971320f4355eeff27c63e46",
          "sha1": "995288a056b58e83cd43d5d770deeda3d2c37950",
          "md5": "0ad3fe97dfbca1132005e815991e8262"
        }
      ]
    },
    {
      "name": "reobfElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "srg",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "AppleCore-3.3.7.jar",
          "url": "AppleCore-3.3.7.jar",
          "size": 101291,
          "sha512": "100c7e622c779686b34489871ea708fd7297fc4588c4a874b2145c5d246bf6800b6cc0709d01160951d4f19ad79af7009927e411043c2ebee1281c250df9471f",
          "sha256": "c4f611f48444da713c2e90bb60120da12f649b5085467e269508276cbd7b7486",
          "sha1": "5fb24bd3aaa6f96487b4efc99ec32017435c5574",
          "md5": "b7a50a973f8a94f5889d219e6092d0cc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "AppleCore-3.3.7-sources.jar",
          "url": "AppleCore-3.3.7-sources.jar",
          "size": 59207,
          "sha512": "532f3d76b2e917a8c31adbf38c6f959bd38520e8b35f252403502f8717bd7105d2c94c3132f2c1f56d0c5dd9755c612726fb792ba195aa09ea8f22a864d62bd0",
          "sha256": "edea0944824de42a98734622b604aa185b5e4184015c5cb62433ea4136d2bc2f",
          "sha1": "89acc5a03a9293c1b98579597e92335ec9dfc5d9",
          "md5": "72988671a30cde388efc92e5a00c3714"
        }
      ]
    }
  ]
}
