{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GTNewHorizons",
    "module": "Eternal-Singularity",
    "version": "1.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "Eternal-Singularity-1.2.1-dev.jar",
          "url": "Eternal-Singularity-1.2.1-dev.jar",
          "size": 141242,
          "sha512": "d676b270d8888f06662c350b46acd92635c4d9af50835722da0e063d151427b483e6ee71091b03fb76a1bee83f268f38eeb58b10a6f41d35b275ee4b6788fc08",
          "sha256": "ce3fec8a5c8f255f74b5157494acd02c8646a7bbee896683630fb4380094986b",
          "sha1": "0a5377e0762659688abc9f4a513c7d48cbf3b65d",
          "md5": "871cb7c4b599d285503357519d72d075"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "NotEnoughItems",
          "version": {
            "requires": "2.5.25-GTNH"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "NotEnoughItems",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "Avaritia",
          "version": {
            "requires": "1.49"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "Avaritia",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "Universal-Singularities",
          "version": {
            "requires": "8.7.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "Universal-Singularities",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "WanionLib",
          "version": {
            "requires": "1.9.0"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "WanionLib",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.2.10"
          },
          "reason": "fixes duplicate mod errors in java 17 configurations using old gtnhlib"
        }
      ],
      "files": [
        {
          "name": "Eternal-Singularity-1.2.1-dev.jar",
          "url": "Eternal-Singularity-1.2.1-dev.jar",
          "size": 141242,
          "sha512": "d676b270d8888f06662c350b46acd92635c4d9af50835722da0e063d151427b483e6ee71091b03fb76a1bee83f268f38eeb58b10a6f41d35b275ee4b6788fc08",
          "sha256": "ce3fec8a5c8f255f74b5157494acd02c8646a7bbee896683630fb4380094986b",
          "sha1": "0a5377e0762659688abc9f4a513c7d48cbf3b65d",
          "md5": "871cb7c4b599d285503357519d72d075"
        }
      ]
    },
    {
      "name": "reobfElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "srg",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Eternal-Singularity-1.2.1.jar",
          "url": "Eternal-Singularity-1.2.1.jar",
          "size": 142803,
          "sha512": "5eece832935e0cd9860c4da1a4e01d2e532b4f38d9f1ad789596e96ee4b58a00fdf52fa73a1816d11364c51a12da1ace3807f3e6d71aa3bd0529a1acae64f408",
          "sha256": "428c5deae5978560cc1b8741d74c278d50c195efaa5a9de94c76de4c1cbc1965",
          "sha1": "c2323ade2016c9ae6051188f73472c196add557e",
          "md5": "ac21e61952452ec309f8e5526d82c746"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Eternal-Singularity-1.2.1-sources.jar",
          "url": "Eternal-Singularity-1.2.1-sources.jar",
          "size": 126966,
          "sha512": "4400c08a120410e250f2805b8c2cbe58a0b00bdd2f415996814d42b614f660dcd648803b58c9203f62d74978749c73d18d7d78dee9e97a650e461c038934dbb0",
          "sha256": "368073d7b4927b619b64d86176499806fd21e7cae8503eec6857db57ad69a82f",
          "sha1": "bcf6bdad27daf172f86999eb2278bd01511e6a69",
          "md5": "103a63420aab77d62c235cc6c4826436"
        }
      ]
    }
  ]
}
