{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GTNewHorizons",
    "module": "ForestryMC",
    "version": "4.10.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "cofh-lib-220333",
          "version": {
            "requires": "2388748"
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "Angelica",
          "version": {
            "requires": "1.0.0-beta51"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "Angelica",
              "type": "jar",
              "extension": "jar",
              "classifier": "api"
            }
          }
        }
      ],
      "files": [
        {
          "name": "ForestryMC-4.10.17-dev.jar",
          "url": "ForestryMC-4.10.17-dev.jar",
          "size": 3365894,
          "sha512": "0c965a8ac95908409903291623accad15d5b63c68a79e9b12ca659df6422819d59fe76875ba59db390f522fb7b8af1d67a3f9e96620ac581f0d051c7357b014d",
          "sha256": "c0a40bc6f2cb9bbe02463c6a1ff2c10632d8c1f8ff4e6c42dc1f95a27a67b673",
          "sha1": "9228668e10e45a7c95a68b6c27cc378131f23715",
          "md5": "9d6c0d3f7a9d9abe3fd19114e955e749"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "curse.maven",
          "module": "cofh-lib-220333",
          "version": {
            "requires": "2388748"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.6.37"
          },
          "reason": "fixes duplicate mod errors in java 17 configurations using old gtnhlib"
        }
      ],
      "files": [
        {
          "name": "ForestryMC-4.10.17-dev.jar",
          "url": "ForestryMC-4.10.17-dev.jar",
          "size": 3365894,
          "sha512": "0c965a8ac95908409903291623accad15d5b63c68a79e9b12ca659df6422819d59fe76875ba59db390f522fb7b8af1d67a3f9e96620ac581f0d051c7357b014d",
          "sha256": "c0a40bc6f2cb9bbe02463c6a1ff2c10632d8c1f8ff4e6c42dc1f95a27a67b673",
          "sha1": "9228668e10e45a7c95a68b6c27cc378131f23715",
          "md5": "9d6c0d3f7a9d9abe3fd19114e955e749"
        }
      ]
    },
    {
      "name": "reobfElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "srg",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ForestryMC-4.10.17.jar",
          "url": "ForestryMC-4.10.17.jar",
          "size": 3394143,
          "sha512": "6695d2e129c76f7f5b270f7eafad1948c8e477f06aed3d89645941261af981a5a47d5ea65a2713b5947a876e519e1bde3176c4b278a5b2fdc22244d92b4e0c6b",
          "sha256": "b537738e29c242726ce7f356985bfd21214f7c8948ea0526e951dbe2f419a3fd",
          "sha1": "db6e152699b5f116164de56c4bca4712f44a1af4",
          "md5": "ce5ea28d227448c72db71eae1e3a4441"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ForestryMC-4.10.17-sources.jar",
          "url": "ForestryMC-4.10.17-sources.jar",
          "size": 2451394,
          "sha512": "4922808f6f609e43454769381a40b8e76acf47a160d2c676d1edb28de742ed78e90cc0bec6db7db40666d3027242fb09805a6845390146eed0de24e8ea5c8f30",
          "sha256": "0cfe326afa87f83131863c99a1c82d201a4286fe58c401b24279d4084192e2be",
          "sha1": "1dcdd6b883bc91d6d19a1678cfa827d61dfc72ef",
          "md5": "9c105fbbfda8d8afb7f5bca117bdd82c"
        }
      ]
    }
  ]
}
