{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GTNewHorizons",
    "module": "WanionLib",
    "version": "1.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "WanionLib-1.10.0-dev.jar",
          "url": "WanionLib-1.10.0-dev.jar",
          "size": 58770,
          "sha512": "14f4d8260932410e5485ea2ba7a71485e537bc26140a760ff6d0fa201176cb0e53f9e61afa0adf57a75df72e9b48da4050209c5b2ef91dcfef3c6c3cbc20ebfb",
          "sha256": "c3487e062dca67929e556664b46d859972918eda9433dae2160b8e46b8cdc760",
          "sha1": "854e2bdaa86424f93a592f12ec0239a4a2392f7b",
          "md5": "7c9fa41195967f3e24864f2e57769f28"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.6.13"
          },
          "reason": "fixes duplicate mod errors in java 17 configurations using old gtnhlib"
        }
      ],
      "files": [
        {
          "name": "WanionLib-1.10.0-dev.jar",
          "url": "WanionLib-1.10.0-dev.jar",
          "size": 58770,
          "sha512": "14f4d8260932410e5485ea2ba7a71485e537bc26140a760ff6d0fa201176cb0e53f9e61afa0adf57a75df72e9b48da4050209c5b2ef91dcfef3c6c3cbc20ebfb",
          "sha256": "c3487e062dca67929e556664b46d859972918eda9433dae2160b8e46b8cdc760",
          "sha1": "854e2bdaa86424f93a592f12ec0239a4a2392f7b",
          "md5": "7c9fa41195967f3e24864f2e57769f28"
        }
      ]
    },
    {
      "name": "reobfElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "srg",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "WanionLib-1.10.0.jar",
          "url": "WanionLib-1.10.0.jar",
          "size": 59380,
          "sha512": "6535267718d938466ed6a7ff54c133d52a7c39d69a3205d4a1914f61c4184adc308806af3b385506c3da2e35cf2d962a14c6f388978c6522882cfb341b138755",
          "sha256": "ac5bef9786a932ce795ffe5fa93b42fbece02fa921c8a9270dda9fc0a8fc9044",
          "sha1": "3de808b4f638a3adb793ac6191f06dd72f36f39a",
          "md5": "eeca1a3e5493173fe50e98ba7b979f0d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "WanionLib-1.10.0-sources.jar",
          "url": "WanionLib-1.10.0-sources.jar",
          "size": 48131,
          "sha512": "27331ebeaa4a1d94fbe2a1aa34d8a52cbbbfb70ffb2ae1e52af8d8bdfd5baa904df49f877a9a274ca0ca2e1eef7bfc9f0b7d0faffbf7214cedc703d04704719f",
          "sha256": "14ac7cccc340aa3c66e049e2a28e0483f4c76e2256e37e7161f97511360a8cc9",
          "sha1": "8ed660fcf53d1361cd8e3e374329ad4492b2db80",
          "md5": "4cc32da6560bb7d0ce23bed9300a0ea9"
        }
      ]
    }
  ]
}
