{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GTNewHorizons",
    "module": "OpenComputers",
    "version": "1.11.19-GTNH",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "OpenComputers-1.11.19-GTNH-dev.jar",
          "url": "OpenComputers-1.11.19-GTNH-dev.jar",
          "size": 16360571,
          "sha512": "e8de2e1832f4a525202da817d5dbd8cc450fb66e5197873abd9585c7cf9ac0563608ff81edfc3dcd019aeb633bba2a5194542a29cd2d264a28e103d574bf8ee6",
          "sha256": "c52ae0dcb59082ac46c6f0b35a86a45ce1759a847094e85d4caf51163fd3da5a",
          "sha1": "ba811ceb98bae309105daa6231895f9a78d44571",
          "md5": "80edda5985dec6c022442252d51efb60"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.6.37"
          },
          "reason": "fixes duplicate mod errors in java 17 configurations using old gtnhlib"
        }
      ],
      "files": [
        {
          "name": "OpenComputers-1.11.19-GTNH-dev.jar",
          "url": "OpenComputers-1.11.19-GTNH-dev.jar",
          "size": 16360571,
          "sha512": "e8de2e1832f4a525202da817d5dbd8cc450fb66e5197873abd9585c7cf9ac0563608ff81edfc3dcd019aeb633bba2a5194542a29cd2d264a28e103d574bf8ee6",
          "sha256": "c52ae0dcb59082ac46c6f0b35a86a45ce1759a847094e85d4caf51163fd3da5a",
          "sha1": "ba811ceb98bae309105daa6231895f9a78d44571",
          "md5": "80edda5985dec6c022442252d51efb60"
        }
      ]
    },
    {
      "name": "reobfElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "srg",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "OpenComputers-1.11.19-GTNH.jar",
          "url": "OpenComputers-1.11.19-GTNH.jar",
          "size": 16480803,
          "sha512": "aa87fe04f6f1474cc309536c244f9d39c72b329ce78c06ebe79015fe71ae184fc771720c6dc2dc2c300a4b8bb1fe6213d6bfae0636c67e2473f751e05c93e33e",
          "sha256": "a900e3a1438e530954a7ca8a12e025cbc6c7160a196e049354bcfd0912e0ac7d",
          "sha1": "f98064cb826ca21c80e27c1a07bf31b988864bf9",
          "md5": "0cbcafac3e32fdb111854d477f00ee27"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "OpenComputers-1.11.19-GTNH-sources.jar",
          "url": "OpenComputers-1.11.19-GTNH-sources.jar",
          "size": 4237676,
          "sha512": "c1e6d2717f7e2a26dbbb0ab7a8de5a70c6400defeb7a0adf1dc202a04cd8a589b0b85b93d0caf4296740d87e22c58915931d3877cd779ffc335aa8d00b42cea4",
          "sha256": "9add2d9f949e3911045d9c4ca750817b9ca9a976f7e4085bd04c95f6e628ac2f",
          "sha1": "8cc4760fc587ae400f7af7d040fe313acee9fe20",
          "md5": "923e58630975574d89ee3da4b2ed4d76"
        }
      ]
    }
  ]
}
