{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GTNewHorizons",
    "module": "Yamcl",
    "version": "0.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "Yamcl-0.7.1-dev.jar",
          "url": "Yamcl-0.7.1-dev.jar",
          "size": 119396,
          "sha512": "6e0c124ce278d7b46be4e511e2613f2323b8ff61d91352af786de7eb99b1743fc27254e18b783b06eb8a521978503700a0829ed381479bb1d3d0680682c65734",
          "sha256": "4d0cc9b77ab1e4aae1307e9e6ba4d0f9f44dbaecaed4220c021b91fb6cd9f54b",
          "sha1": "f14519f52e7b993809f3b7fb400f6446fabd4458",
          "md5": "53d08bc92e17ab81615e7f23cbb5a297"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.6.13"
          },
          "reason": "fixes duplicate mod errors in java 17 configurations using old gtnhlib"
        }
      ],
      "files": [
        {
          "name": "Yamcl-0.7.1-dev.jar",
          "url": "Yamcl-0.7.1-dev.jar",
          "size": 119396,
          "sha512": "6e0c124ce278d7b46be4e511e2613f2323b8ff61d91352af786de7eb99b1743fc27254e18b783b06eb8a521978503700a0829ed381479bb1d3d0680682c65734",
          "sha256": "4d0cc9b77ab1e4aae1307e9e6ba4d0f9f44dbaecaed4220c021b91fb6cd9f54b",
          "sha1": "f14519f52e7b993809f3b7fb400f6446fabd4458",
          "md5": "53d08bc92e17ab81615e7f23cbb5a297"
        }
      ]
    },
    {
      "name": "reobfElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "srg",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Yamcl-0.7.1.jar",
          "url": "Yamcl-0.7.1.jar",
          "size": 122149,
          "sha512": "03b9ff9f20ddf480a574c1dd782fcb78dbcc50a74e87c2b5067f5f02234491ab8dec81b2aacd3039284cc9dd9d29c684b0f4d436cb5dfde2178b6c47955de8cd",
          "sha256": "eaa6349c892798eb1d79a0df2078630e553b12a6f93a4ae64c3e34373a30c80d",
          "sha1": "0c8af1c6c8228691d0a643a8a57e92d4291e9fe0",
          "md5": "b33a25548bb3e4b727dbf399259eb0a3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Yamcl-0.7.1-sources.jar",
          "url": "Yamcl-0.7.1-sources.jar",
          "size": 76715,
          "sha512": "edb684386cc2b38e6c6b85df21a94189e482631c331b3e7e7500ceba31604c418f0b22c9154d82dafe6e89afc3d9d90d5e6d3eed415faa30284eb99a1a85b7df",
          "sha256": "6eb1d72e788b221a58452bcd73325610bd2bf69204dfa9a2a91a5a6e8f967c79",
          "sha1": "51cb471c23220218a9a2503b9f86b7214a9973e2",
          "md5": "86b2e6e6a83cf5d11d769ddc26de9f7a"
        }
      ]
    }
  ]
}
