{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.GTNewHorizons",
    "module": "ThaumicBoots",
    "version": "1.4.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "thaumcraft",
          "module": "Thaumcraft",
          "version": {
            "requires": "1.7.10-4.2.3.5"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "Thaumcraft",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "Baubles-Expanded",
          "version": {
            "requires": "2.1.9-GTNH"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "Baubles-Expanded",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "Thaumic_Exploration",
          "version": {
            "requires": "1.4.2-GTNH"
          },
          "excludes": [
            {
              "group": "com.github.GTNewHorizons",
              "module": "ThaumicBoots"
            },
            {
              "group": "*",
              "module": "Baubles"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "Thaumic_Exploration",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "Electro-Magic-Tools",
          "version": {
            "requires": "1.6.11"
          },
          "excludes": [
            {
              "group": "com.github.GTNewHorizons",
              "module": "ThaumicBoots"
            },
            {
              "group": "*",
              "module": "Baubles"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "Electro-Magic-Tools",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "Tainted-Magic",
          "version": {
            "requires": "7.6.25-GTNH"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.6.38"
          }
        }
      ],
      "files": [
        {
          "name": "ThaumicBoots-1.4.14-dev.jar",
          "url": "ThaumicBoots-1.4.14-dev.jar",
          "size": 1543607,
          "sha512": "d532cb4c4dd9836132b1c20adc9cf8368764833c4cdf6e64d3167de4773cef7fc103dc566e6bc135423c56d3993f2562cd5429a509b4e1fef9a454e36ef0dc42",
          "sha256": "10bb0bb7e13550024945d4697f5f34349077017aee69bc596096cbd2ef0a5d74",
          "sha1": "f245816176a49423c2754ad40789229b1f434c6a",
          "md5": "f137760a67ee54ae0b32816c4f296780"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.github.legacymoddingmc",
          "module": "unimixins",
          "version": {
            "requires": "0.1.22"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "unimixins",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "thaumcraft",
          "module": "Thaumcraft",
          "version": {
            "requires": "1.7.10-4.2.3.5"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "Thaumcraft",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "Baubles-Expanded",
          "version": {
            "requires": "2.1.9-GTNH"
          },
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "Baubles-Expanded",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "Thaumic_Exploration",
          "version": {
            "requires": "1.4.2-GTNH"
          },
          "excludes": [
            {
              "group": "com.github.GTNewHorizons",
              "module": "ThaumicBoots"
            },
            {
              "group": "*",
              "module": "Baubles"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "Thaumic_Exploration",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "Electro-Magic-Tools",
          "version": {
            "requires": "1.6.11"
          },
          "excludes": [
            {
              "group": "com.github.GTNewHorizons",
              "module": "ThaumicBoots"
            },
            {
              "group": "*",
              "module": "Baubles"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "Electro-Magic-Tools",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "Tainted-Magic",
          "version": {
            "requires": "7.6.25-GTNH"
          },
          "excludes": [
            {
              "group": "*",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.6.38"
          }
        },
        {
          "group": "com.github.GTNewHorizons",
          "module": "TCNEIAdditions",
          "version": {
            "requires": "1.5.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "Baubles"
            }
          ],
          "thirdPartyCompatibility": {
            "artifactSelector": {
              "name": "TCNEIAdditions",
              "type": "jar",
              "extension": "jar",
              "classifier": "dev"
            }
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "com.github.GTNewHorizons",
          "module": "GTNHLib",
          "version": {
            "requires": "0.6.37"
          },
          "reason": "fixes duplicate mod errors in java 17 configurations using old gtnhlib"
        }
      ],
      "files": [
        {
          "name": "ThaumicBoots-1.4.14-dev.jar",
          "url": "ThaumicBoots-1.4.14-dev.jar",
          "size": 1543607,
          "sha512": "d532cb4c4dd9836132b1c20adc9cf8368764833c4cdf6e64d3167de4773cef7fc103dc566e6bc135423c56d3993f2562cd5429a509b4e1fef9a454e36ef0dc42",
          "sha256": "10bb0bb7e13550024945d4697f5f34349077017aee69bc596096cbd2ef0a5d74",
          "sha1": "f245816176a49423c2754ad40789229b1f434c6a",
          "md5": "f137760a67ee54ae0b32816c4f296780"
        }
      ]
    },
    {
      "name": "reobfElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "srg",
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ThaumicBoots-1.4.14.jar",
          "url": "ThaumicBoots-1.4.14.jar",
          "size": 1548464,
          "sha512": "01f6528aca30c22673ea35ccf9ebbbc443546e884b25697f8d7242862f03483188f7e5897db6c78b864ec3fbd8978974432efe444eac670798aeded5f4994217",
          "sha256": "7b7564a255f22d7a1c073b16a8cc34ed2815112eb9e8e1685f3a8144e27c10c5",
          "sha1": "941aeac44e098b9b46fde2038b5aed45beb076f9",
          "md5": "ce810e599e8fc7cd37a38071122d0e7d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "com.gtnewhorizons.retrofuturagradle.obfuscation": "mcp",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ThaumicBoots-1.4.14-sources.jar",
          "url": "ThaumicBoots-1.4.14-sources.jar",
          "size": 1488510,
          "sha512": "c7c9e5a32a2d8157eeefc5a1de760368462c3f936f116892a4fe466b9685299d2f9c80c49b03527a4a41bf6372e92769681881b0b1d231b7a4acaa517d5ff209",
          "sha256": "6ed56fb686892747c5c0710d32c2d220db05d3cec9a37057a9765abf7a515bad",
          "sha1": "191d8c94acad4a8eaf95dd7230f00ccbc2291c44",
          "md5": "b000a050b38617bca25873dd04f6ccd4"
        }
      ]
    }
  ]
}
